name: Datapack Bug Report
description: Submit a datapack bug report.
title: "(D.E) "
labels: 
- "bug :bug:"
assignees:
- legopitstop
body:
 - type: markdown
   attributes:
     value: |
      Note: Please search to see if an issue already exists for the bug you encountered.

 - type: dropdown
   id: edition
   validations:
     required: true
   attributes:
     label: What Edition of the mod are you using?
     description: The Minecraft platform where the issue is taking place
     multiple: false
     options:
       - Bedrock
       - Forge
       - Datapack

 - type: textarea
   id: describe
   validations:
     required: true
   attributes:
     label: Describe the bug
     description: A clear and concise description of what the bug is.

 - type: textarea
   id: reproduce
   validations:
     required: true
   attributes:
     label: Steps To Reproduce
     description: Steps to reproduce the behavior
     value: |
      1.
      2.
      3.
      ...


 - type: textarea
   id: expected
   validations:
     required: true
   attributes:
     label: Expected behavior
     description: A clear and concise description of what you expected to happen.

 - type: input
   id: minecraft_version
   validations:
     required: true
   attributes:
     label: Minecraft Version
     description: The version of Minecraft that you are using this mod on.
     placeholder: e.g. 1.18.2

 - type: dropdown
   id: mod_version
   validations:
     required: true
   attributes:
     label: Mod Version
     description: The version of the Mod that you are using.
     options:
       - "newer"
       - "3.1"
       - "3.0"
       - "2.9"
       - "2.8"
       - "2.7"
       - "2.6"
       - "2.5"
       - "2.4"
       - "2.3"
       - "2.2"
       - "2.1"
       - "2.0"
       - "1.9"
       - "1.8"
       - "1.7"
       - "1.6"
       - "1.5-fix"
       - "1.5"
       - "1.4"
       - "1.3-fix"
       - "1.3"
       - "1.2"
       - "1.1"
       - "Update 2"
       - "Beta"
       - "older"

 - type: input
   id: platform
   attributes:
     label: Platform
     description: The device that you are using this mod on. 
     placeholder: e.g. iOS, win10

 - type: textarea
   id: other
   attributes:
     label: Additional context
     description: |
      Add any other information about the problem here.
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

