name: Feature Request
description: Suggest an idea for this project
labels: 
- "Suggestion :bulb:"
assignees:
- legopitstop
body:
 - type: markdown
   attributes:
     value: |
      Note: Use the `/idea` command in the Lot's More Food Discord server for suggesting new items/foods.

 - type: textarea
   id: feature
   validations:
     required: true
   attributes:
     label: Describe the solution you'd like
     description: A clear and concise description of what you want to happen.

 - type: textarea
   id: rel_issue
   attributes:
     label: Is your feature request related to a problem? Please describe.
     description: A clear and concise description of what the problem is.
     placeholder: I'm always frustrated when [...]

 - type: dropdown
   id: edition
   attributes:
     label: Prefered Edition
     description: The Minecraft Edition you would like to see this feature added to.
     options:
       - unset
       - Bedrock
       - Datapack
       - Forge
       - Fabric

 - type: textarea
   id: other
   attributes:
     label: Additional context
     description: |
      Add any other information about the problem here.
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.