give @s morefood:cooked_beef_block
give @s morefood:cooked_chicken_block
give @s morefood:cooked_mutton_block
give @s morefood:cooked_rabbit_block
give @s morefood:cooked_squid_block
give @s morefood:cookie_block
give @s morefood:dark_chocolate_block
give @s morefood:golden_apple_block
give @s morefood:milk_chocolate_block
give @s morefood:mutton_block
give @s morefood:potato_block
give @s morefood:rabbit_block
give @s morefood:squid_block
give @s morefood:white_chocolate_block
give @s morefood:corn_crop
give @s morefood:gherkin_bush
give @s morefood:grape_bush
give @s morefood:hanging_coconut
give @s morefood:hops_crop
give @s morefood:lemon_hanging_fruit
give @s morefood:lemon_sapling_block
give @s morefood:lettuce_crop
give @s morefood:olives_hanging_fruit
give @s morefood:olive_sapling_block
give @s morefood:onion_crop
give @s morefood:orange_hanging_fruit
give @s morefood:orange_sapling_block
give @s morefood:palm_sapling_block
give @s morefood:pepper_bush
give @s morefood:plum_hanging_fruit
give @s morefood:plum_sapling_block
give @s morefood:pound_cake_block
give @s morefood:rainbow_cake_block
give @s morefood:raspberry_bush
give @s morefood:redwhiteblue_cake_block
give @s morefood:rice_crop
