give @s morefood:apple_block
give @s morefood:baked_potato_block
#give @s morefood:banana_block
give @s morefood:beef_block
give @s morefood:carrot_block
give @s morefood:chicken_block
give @s morefood:cooked_beef_block
give @s morefood:cooked_chicken_block
give @s morefood:cooked_mutton_block
give @s morefood:cooked_rabbit_block
give @s morefood:cooked_squid_block
give @s morefood:cookie_block
give @s morefood:dark_chocolate_block
give @s morefood:golden_apple_block
#give @s morefood:grape_block
#give @s morefood:hops_block
#give @s morefood:lemon_block
give @s morefood:milk_chocolate_block
give @s morefood:mutton_block
#give @s morefood:olive_block
#give @s morefood:orange_block
#give @s morefood:plum_block
give @s morefood:potato_block
give @s morefood:rabbit_block
#give @s morefood:raspberry_block
give @s morefood:squid_block
#give @s morefood:strawberry_block
#give @s morefood:tomato_block
give @s morefood:white_chocolate_block