gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 5/7 items."}]}
give @s morefood:pizza
give @s morefood:pizza_base
give @s morefood:popcorn
give @s morefood:popcorn_bucket
give @s morefood:ramen_noodles
give @s morefood:raw_hamburger_patty
give @s morefood:raw_sausage
give @s morefood:raw_squid
give @s morefood:raw_veganburger_patty
give @s morefood:raw_wedges
give @s morefood:rice
give @s morefood:rice_pudding
give @s morefood:round_cheese
give @s morefood:salt
give @s morefood:sashimi
give @s morefood:sausage_egg_muffin
give @s morefood:sausage_egg_sandwich
give @s morefood:spaghetti
give @s morefood:sparkling_water_bucket
give @s morefood:strawberry_jelly
give @s morefood:sub_bun
give @s morefood:sushi
give @s morefood:taco
give @s morefood:tea_leaves
give @s morefood:toast
give @s morefood:toffee
give @s morefood:toffee_latte
give @s morefood:tomato_puree
give @s morefood:tortilla
give @s morefood:turkish_delight
give @s morefood:vanilla_extract
give @s morefood:vanilla_latte
give @s morefood:vanilla_pod
give @s morefood:veganburger
give @s morefood:veganburger_patty
give @s morefood:waffle
gamerule sendcommandfeedback true