gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 4/6 items."}]}
give @p morefood:coconut_milk
give @p morefood:cooked_bacon
give @p morefood:cooked_bat_meat
give @p morefood:cooked_hotdog_sausage
give @p morefood:cooked_sausage
give @p morefood:cornflour
give @p morefood:cream_carton
give @p morefood:custard
give @p morefood:cut_bread
give @p morefood:cut_fries
give @p morefood:dark_chocolate
give @p morefood:dough
give @p morefood:flour
give @p morefood:fried_egg
give @p morefood:fried_squid
give @p morefood:fries
give @p morefood:gelatin
give @p morefood:hamburger
give @p morefood:hamburger_patty
give @p morefood:hops
give @p morefood:hotdog
give @p morefood:hotdog_bun
give @p morefood:hotdog_sausage
give @p morefood:ice_bowl
give @p morefood:kebab
give @p morefood:milk_carton
give @p morefood:milk_chocolate
give @p morefood:muffin_bun
give @p morefood:noodles
give @p morefood:oil
give @p morefood:onigiri
give @p morefood:orange_jelly
give @p morefood:pancakes
give @p morefood:pasta
give @p morefood:pink_cupcake
give @p morefood:pitta_bread
gamerule sendcommandfeedback true