gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 3/7 items."}]}
give @s morefood:smoothie_banana
give @s morefood:smoothie_berry
give @s morefood:smoothie_grape
give @s morefood:smoothie_mixed_fruit
give @s morefood:smoothie_raspberry
give @s morefood:smoothie_strawberry
give @s morefood:soda_apple
give @s morefood:soda_berry
give @s morefood:soda_grape
give @s morefood:soda_lemon
give @s morefood:soda_orange
give @s morefood:soda_strawberry
give @s morefood:corn_on_cob
give @s morefood:gherkin
give @s morefood:lettuce
give @s morefood:onion
give @s morefood:pickles
give @s morefood:bacon
give @s morefood:bacon_egg_muffin
give @s morefood:bacon_egg_sandwich
give @s morefood:bat_meat
give @s morefood:beef_sub
give @s morefood:blue_cupcake
give @s morefood:bread_loaf
give @s morefood:breakfast_sub
give @s morefood:burger_bun
give @s morefood:burrito
give @s morefood:butter
give @s morefood:cereal
give @s morefood:cheese_bucket
give @s morefood:cheese_toastie
give @s morefood:cheese_wedge
give @s morefood:chicken_fajita
give @s morefood:chicken_select
give @s morefood:chicken_sub
give @s morefood:coconut_meat
gamerule sendcommandfeedback true