gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 2/7 items."}]}
give @s morefood:icecream_toffee
give @s morefood:icecream_vanilla
give @s morefood:icecrush_apple
give @s morefood:icecrush_apple_raspberry
give @s morefood:icecrush_berry
give @s morefood:icecrush_grape
give @s morefood:icecrush_lemon
give @s morefood:icecrush_melon
give @s morefood:icecrush_mixed_fruit
give @s morefood:icecrush_strawberry
give @s morefood:icecrush_orange
give @s morefood:juice_apple
give @s morefood:juice_berry
give @s morefood:juice_grape
give @s morefood:juice_lemon
give @s morefood:juice_mixed_fruit
give @s morefood:juice_orange
give @s morefood:juice_strawberry
give @s morefood:juice_tomato
give @s morefood:milkshake_banana
give @s morefood:milkshake_chocolate
give @s morefood:milkshake_strawberry
give @s morefood:pie_apple
give @s morefood:pie_apple_raspberry
give @s morefood:pie_base
give @s morefood:pie_berry
give @s morefood:pie_cheese
give @s morefood:pie_chicken
give @s morefood:pie_chocolate
give @s morefood:pie_lemon
give @s morefood:pie_plum
give @s morefood:pie_pork
give @s morefood:pie_steak
give @s morefood:pie_strawberry
give @s morefood:pie_toffee
gamerule sendcommandfeedback true