gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 2/6 items."}]}
give @p morefood:icecream_toffee
give @p morefood:icecream_vanilla
give @p morefood:icecrush_apple
give @p morefood:icecrush_apple_raspberry
give @p morefood:icecrush_berry
give @p morefood:icecrush_grape
give @p morefood:icecrush_lemon
give @p morefood:icecrush_melon
give @p morefood:icecrush_mixed_fruit
give @p morefood:icecrush_strawberry
give @p morefood:icecrush_orange
give @p morefood:juice_apple
give @p morefood:juice_berry
give @p morefood:juice_grape
give @p morefood:juice_lemon
give @p morefood:juice_mixed_fruit
give @p morefood:juice_orange
give @p morefood:juice_strawberry
give @p morefood:juice_tomato
give @p morefood:milkshake_banana
give @p morefood:milkshake_chocolate
give @p morefood:milkshake_strawberry
give @p morefood:pie_apple
give @p morefood:pie_apple_raspberry
give @p morefood:pie_base
give @p morefood:pie_berry
give @p morefood:pie_cheese
give @p morefood:pie_chicken
give @p morefood:pie_chocolate
give @p morefood:pie_golden_apple
give @p morefood:pie_lemon
give @p morefood:pie_plum
give @p morefood:pie_pork
give @p morefood:pie_steak
give @p morefood:pie_strawberry
give @p morefood:pie_toffee
gamerule sendcommandfeedback true