gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 3/6 items."}]}
give @p morefood:smoothie_banana
give @p morefood:smoothie_berry
give @p morefood:smoothie_grape
give @p morefood:smoothie_mixed_fruit
give @p morefood:smoothie_raspberry
give @p morefood:smoothie_strawberry
give @p morefood:soda_apple
give @p morefood:soda_berry
give @p morefood:soda_grape
give @p morefood:soda_lemon
give @p morefood:soda_orange
give @p morefood:soda_strawberry
give @p morefood:corn_on_cob
give @p morefood:gherkin
give @p morefood:lettuce
give @p morefood:onion
give @p morefood:pickles
give @p morefood:bacon
give @p morefood:bacon_egg_muffin
give @p morefood:bacon_egg_sandwich
give @p morefood:bat_meat
give @p morefood:beef_sub
give @p morefood:blue_cupcake
give @p morefood:bread_loaf
give @p morefood:breakfast_sub
give @p morefood:burger_bun
give @p morefood:burrito
give @p morefood:butter
give @p morefood:cereal
give @p morefood:cheese_bucket
give @p morefood:cheese_toastie
give @p morefood:cheese_wedge
give @p morefood:chicken_fajita
give @p morefood:chicken_select
give @p morefood:chicken_sub
give @p morefood:coconut_meat
gamerule sendcommandfeedback true