gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 1/7 items."}]}
give @s morefood:beer
give @s morefood:bottled_beer
give @s morefood:bottled_cider
give @s morefood:bottled_red_wine
give @s morefood:bottled_white_wine
give @s morefood:cider
give @s morefood:red_wine
give @s morefood:white_wine
give @s morefood:americano
give @s morefood:cappuccino
give @s morefood:hot_cocoa
give @s morefood:hot_coffee
give @s morefood:hot_tea
give @s morefood:macchiato
give @s morefood:mocha
give @s morefood:donut_chocolate
give @s morefood:donut_coffee
give @s morefood:donut_iced
give @s morefood:donut_pink_ice
give @s morefood:donut_plain
give @s morefood:donut_strawberry
give @s morefood:donut_toffee
give @s morefood:banana
give @s morefood:grape
give @s morefood:lemon
give @s morefood:olives
give @s morefood:orange
give @s morefood:plum
give @s morefood:raspberry
give @s morefood:strawberry
give @s morefood:tomato
give @s morefood:icecream_banana
give @s morefood:icecream_chocolate
give @s morefood:icecream_cone
give @s morefood:icecream_strawberry
gamerule sendcommandfeedback true