gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 4/7 items."}]}
give @s morefood:coconut_milk
give @s morefood:cooked_bacon
give @s morefood:cooked_bat_meat
give @s morefood:cooked_hotdog_sausage
give @s morefood:cooked_sausage
give @s morefood:cornflour
give @s morefood:cream_carton
give @s morefood:custard
give @s morefood:cut_bread
give @s morefood:cut_fries
give @s morefood:dark_chocolate
give @s morefood:dough
give @s morefood:flour
give @s morefood:fried_egg
give @s morefood:fried_squid
give @s morefood:fries
give @s morefood:gelatin
give @s morefood:hamburger
give @s morefood:hamburger_patty
give @s morefood:hops
give @s morefood:hotdog
give @s morefood:hotdog_bun
give @s morefood:hotdog_sausage
give @s morefood:ice_bowl
give @s morefood:kebab
give @s morefood:milk_carton
give @s morefood:milk_chocolate
give @s morefood:muffin_bun
give @s morefood:noodles
give @s morefood:oil
give @s morefood:onigiri
give @s morefood:orange_jelly
give @s morefood:pancakes
give @s morefood:pasta
give @s morefood:pink_cupcake
give @s morefood:pitta_bread
gamerule sendcommandfeedback true