gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 5/6 items."}]}
give @p morefood:pizza
give @p morefood:pizza_base
give @p morefood:popcorn
give @p morefood:popcorn_bucket
give @p morefood:ramen_noodles
give @p morefood:raw_hamburger_patty
give @p morefood:raw_sausage
give @p morefood:raw_squid
give @p morefood:raw_veganburger_patty
give @p morefood:raw_wedges
give @p morefood:rice
give @p morefood:rice_pudding
give @p morefood:round_cheese
give @p morefood:salt
give @p morefood:sashimi
give @p morefood:sausage_egg_muffin
give @p morefood:sausage_egg_sandwich
give @p morefood:spaghetti
give @p morefood:sparkling_water_bucket
give @p morefood:strawberry_jelly
give @p morefood:sub_bun
give @p morefood:sushi
give @p morefood:taco
give @p morefood:tea_leaves
give @p morefood:toast
give @p morefood:toffee
give @p morefood:toffee_latte
give @p morefood:tomato_puree
give @p morefood:tortilla
give @p morefood:turkish_delight
give @p morefood:vanilla_extract
give @p morefood:vanilla_latte
give @p morefood:vanilla_pod
give @p morefood:veganburger
give @p morefood:veganburger_patty
give @p morefood:waffle
gamerule sendcommandfeedback true