gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 6/7 items."}]}
give @s morefood:wedges_pot
give @s morefood:white_chocolate
give @s morefood:yeast
give @s morefood:ketchup
give @s morefood:chocolate_cake
give @s morefood:rainbow_cake
give @s morefood:redwhiteblue_cake
give @s morefood:nether_cookie
give @s morefood:hoglin_meat
give @s morefood:cooked_hoglin_meat
give @s morefood:fungus_stew
give @s morefood:netherwart_chicken_soup
give @s morefood:netherwart_mushroom_soup
give @s morefood:rotten_porkchop
give @s morefood:shroomlight_slices
give @s morefood:warped_berries
give @s morefood:wart_pie
give @s morefood:netherite_apple
give @s morefood:cooked_chicken_piece
give @s morefood:cooked_wedges
give @s morefood:pepper
give @s morefood:sparkling_water_bottle
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
gamerule sendcommandfeedback true