gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 6/6 items."}]}
give @p morefood:wedges_pot
give @p morefood:white_chocolate
give @p morefood:yeast
give @p morefood:ketchup
give @p morefood:chocolate_cake
give @p morefood:rainbow_cake
give @p morefood:redwhiteblue_cake
give @p morefood:nether_cookie
give @p morefood:hoglin_meat
give @p morefood:cooked_hoglin_meat
give @p morefood:fungus_stew
give @p morefood:netherwart_chicken_soup
give @p morefood:netherwart_mushroom_soup
give @p morefood:rotten_porkchop
give @p morefood:shroomlight_slices
give @p morefood:warped_berries
give @p morefood:wart_pie
give @p morefood:netherite_apple
give @p morefood:cooked_chicken_piece
give @p morefood:cooked_wedges
give @p morefood:pepper
give @p morefood:sparkling_water_bottle
#give @p morefood:
#give @p morefood:
#give @p morefood:
#give @p morefood:
#give @p morefood:
#give @p morefood:
#give @p morefood:
#give @p morefood:
#give @p morefood:
#give @p morefood:
#give @p morefood:
#give @p morefood:
#give @p morefood:
#give @p morefood:
#give @p morefood:
gamerule sendcommandfeedback true