gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all food 1/6 items."}]}
give @p morefood:beer
give @p morefood:bottled_beer
give @p morefood:bottled_cider
give @p morefood:bottled_red_wine
give @p morefood:bottled_white_wine
give @p morefood:cider
give @p morefood:red_wine
give @p morefood:white_wine
give @p morefood:americano
give @p morefood:cappuccino
give @p morefood:hot_cocoa
give @p morefood:hot_coffee
give @p morefood:hot_tea
give @p morefood:macchiato
give @p morefood:mocha
give @p morefood:donut_chocolate
give @p morefood:donut_coffee
give @p morefood:donut_golden
give @p morefood:donut_iced
give @p morefood:donut_pink_ice
give @p morefood:donut_plain
give @p morefood:donut_strawberry
give @p morefood:donut_toffee
give @p morefood:banana
give @p morefood:grape
give @p morefood:lemon
give @p morefood:olives
give @p morefood:orange
give @p morefood:plum
give @p morefood:raspberry
give @p morefood:strawberry
give @p morefood:tomato
give @p morefood:icecream_banana
give @p morefood:icecream_chocolate
give @p morefood:icecream_cone
give @p morefood:icecream_strawberry
gamerule sendcommandfeedback true