gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all Ingredient items."}]}
give @s morefood:butter
give @s morefood:cheese_wedge
give @s morefood:cornflour
give @s morefood:cream_carton
give @s morefood:cut_fries
give @s morefood:flour
give @s morefood:gelatin
give @s morefood:ketchup
give @s morefood:milk_carton
give @s morefood:noodles
give @s morefood:oil
give @s morefood:pasta
give @s morefood:pickles
give @s morefood:raw_wedges
give @s morefood:round_cheese
give @s morefood:salt
give @s morefood:starch
give @s morefood:tomato_puree
give @s morefood:vanilla_extract
give @s morefood:yeast
give @s morefood:beer_glass
give @s morefood:beverage_cup
give @s morefood:bottle
give @s morefood:carton
give @s morefood:chicken_select_box
give @s morefood:empty_icecrush_glass
give @s morefood:empty_tumbler_glass
give @s morefood:fry_wrapper
give @s morefood:hot_beverage_cup
give @s morefood:icing
give @s morefood:jar
give @s morefood:soda_can_empty
give @s morefood:sub_wrapper
give @s morefood:wine_glass
#give @s morefood:
#give @s morefood:
gamerule sendcommandfeedback true