give @s morefood:crackers_with_chocolate_peanut_butter
give @s morefood:crackers_with_glowberry_jam
give @s morefood:crackers_with_jalapeno_cheese
give @s morefood:crackers_with_jam
give @s morefood:crackers_with_peanut_butter
give @s morefood:cranberries
give @s morefood:cranberry_seeds
give @s morefood:cut_bread_with_cheese
give @s morefood:cut_bread_with_chocolate_peanut_butter
give @s morefood:cut_bread_with_glowberry_jam
give @s morefood:cut_bread_with_jalapeno_cheese
give @s morefood:cut_bread_with_jam
give @s morefood:cut_bread_with_peanut_butter
give @s morefood:cut_sweet_potato
give @s morefood:dark_chocolate_covered_apple
give @s morefood:dried_cranberries
give @s morefood:dried_raisens
give @s morefood:chocolate_protein_drink
give @s morefood:cocoa_beverage
give @s morefood:glowberry_icecrush
give @s morefood:glowberry_juice
give @s morefood:glowberry_smoothie
give @s morefood:glowberry_soda
give @s morefood:grape_beverage
give @s morefood:lemon_lime_beverage
give @s morefood:orange_beverage
give @s morefood:tropical_punch_beverage
give @s morefood:eggplant
give @s morefood:eggplant_seeds
give @s morefood:garlic
give @s morefood:garlic_bulb
give @s morefood:garlic_mashed_potatoes
give @s morefood:glass_shard
give @s morefood:glowberry_jam
give @s morefood:glowberry_jelly_sandwich
give @s morefood:glowberry_pie
