give @s morefood:popcorn
give @s morefood:popcorn_bucket
give @s morefood:rainbow_cake
give @s morefood:ramen_noodles
give @s morefood:raspberry
give @s morefood:raspberry_seeds
give @s morefood:redwhiteblue_cake
give @s morefood:rice
give @s morefood:rice_pudding
give @s morefood:rice_seeds
give @s morefood:rotten_porkchop
give @s morefood:round_cheese
give @s morefood:salt
give @s morefood:sashimi
give @s morefood:raw_sausage
give @s morefood:sausage_egg_muffin
give @s morefood:sausage_egg_sandwich
give @s morefood:shroomlight_slices
give @s morefood:soda_can_empty
give @s morefood:spaghetti
give @s morefood:sparkling_water_bucket
give @s morefood:raw_squid
give @s morefood:starch
give @s morefood:knife_stone
give @s morefood:strawberry
give @s morefood:strawberry_jelly
give @s morefood:strawberry_seeds
give @s morefood:sub_bun
give @s morefood:sub_wrapper
give @s morefood:sushi
give @s morefood:taco
give @s morefood:tea_leaves
give @s morefood:tea_seeds
give @s morefood:toast
give @s morefood:toffee
give @s morefood:tomato
