give @s morefood:milkshake_chocolate
give @s morefood:milkshake_strawberry
give @s morefood:milk_carton
give @s morefood:mocha
give @s morefood:oil
give @s morefood:red_wine
give @s morefood:smoothie_banana
give @s morefood:smoothie_berry
give @s morefood:smoothie_grape
give @s morefood:smoothie_mixed_fruit
give @s morefood:smoothie_raspberry
give @s morefood:smoothie_strawberry
give @s morefood:soda_apple
give @s morefood:soda_berry
give @s morefood:soda_grape
give @s morefood:soda_lemon
give @s morefood:soda_orange
give @s morefood:soda_strawberry
give @s morefood:sparkling_water_bottle
give @s morefood:toffee_latte
give @s morefood:vanilla_extract
give @s morefood:vanilla_latte
give @s morefood:white_wine
give @s morefood:empty_icecrush_glass
give @s morefood:empty_tumbler_glass
give @s morefood:flour
give @s morefood:fried_egg
give @s morefood:fried_squid
give @s morefood:fries
give @s morefood:fry_wrapper
give @s morefood:fungus_stew
give @s morefood:gelatin
give @s morefood:gherkin
give @s morefood:gherkin_seeds
