gamerule sendcommandfeedback false
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all item items."}]}
give @s morefood:beer_glass
give @s morefood:beverage_cup
give @s morefood:bottle
give @s morefood:carton
give @s morefood:chicken_select_box
give @s morefood:cream_carton
give @s morefood:empty_icecrush_glass
give @s morefood:empty_popcorn_bucket
give @s morefood:empty_tumbler_glass
give @s morefood:empty_wedges_pot
give @s morefood:fry_wrapper
give @s morefood:hot_beverage_cup
give @s morefood:icing
give @s morefood:jar
give @s morefood:soda_can_empty
give @s morefood:starch
give @s morefood:sub_wrapper
give @s morefood:wine_glass
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
gamerule sendcommandfeedback true