give @s morefood:cooked_hoglin_meat
give @s morefood:cooked_hotdog_sausage
give @s morefood:cooked_sausage
give @s morefood:veganburger_patty
give @s morefood:cooked_wedges
give @s morefood:copper_knife
give @s morefood:corn
give @s morefood:cornflour
give @s morefood:corn_on_cob
give @s morefood:creative_hunger
give @s morefood:custard
give @s morefood:cut_bread
give @s morefood:cut_fries
give @s morefood:dark_chocolate
give @s morefood:knife_diamond
give @s morefood:donut_chocolate
give @s morefood:donut_coffee
give @s morefood:donut_iced
give @s morefood:donut_pink_ice
give @s morefood:donut_plain
give @s morefood:donut_strawberry
give @s morefood:donut_toffee
give @s morefood:dough
give @s morefood:americano
give @s morefood:beer
give @s morefood:bottled_beer_0
give @s morefood:bottled_beer
give @s morefood:bottled_beer_25
give @s morefood:bottled_beer_50
give @s morefood:bottled_beer_75
give @s morefood:bottled_cider_0
give @s morefood:bottled_cider
give @s morefood:bottled_cider_25
give @s morefood:bottled_cider_50
give @s morefood:bottled_cider_75
give @s morefood:bottled_red_wine_0
