gamerule sendCommandFeedback true
tellraw @s {"rawtext":[{"text":"§f<"},{"text":"§6Lot's More Food"},{"text":"§f>"},{"text":"§c Given all tool items."}]}
give @s morefood:onion_seeds
give @s morefood:lettuce_seeds
give @s morefood:hops_seeds
give @s morefood:grape_seeds
give @s morefood:gherkin_seeds
give @s morefood:barley_seeds
give @s morefood:vanilla_seeds
give @s morefood:tomato_seeds
give @s morefood:tea_seeds
give @s morefood:strawberry_seeds
give @s morefood:rice_seeds
give @s morefood:raspberry_seeds
give @s morefood:coffee_beans
give @s morefood:pepper_seeds
give @s morefood:corn
give @s morefood:palm_sapling
give @s morefood:apple_sapling
give @s morefood:banana_sapling
give @s morefood:lemon_sapling
give @s morefood:olive_sapling
give @s morefood:orange_sapling
give @s morefood:plum_sapling
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
#give @s morefood:
gamerule sendCommandFeedback true