give @s morefood:banana_sack
give @s morefood:coconut_sack
give @s morefood:corn_cob_sack
give @s morefood:gherkin_sack
give @s morefood:grape_sack
give @s morefood:hops_sack
give @s morefood:lemon_sack
give @s morefood:lettuce_sack
give @s morefood:olive_sack
give @s morefood:onion_sack
give @s morefood:orange_sack
give @s morefood:pepper_sack
give @s morefood:plum_sack
give @s morefood:raspberry_sack
give @s morefood:rice_sack
give @s morefood:strawberry_sack
give @s morefood:tea_leaf_sack
give @s morefood:tomato_sack
give @s morefood:vanilla_pod_sack
give @s morefood:almond_sack
give @s morefood:avocado_sack
give @s morefood:bean_sack
give @s morefood:cabbage_sack
give @s morefood:cranberry_sack
give @s morefood:eggplant_sack
give @s morefood:garlic_sack
give @s morefood:oat_sack
give @s morefood:peanut_sack
give @s morefood:poisonous_sweet_potato_sack
give @s morefood:poison_berry_sack
give @s morefood:spinach_sack
give @s morefood:blueberry_sack
give @s morefood:chocolate_chunk_oatmeal_cookie_sack
give @s morefood:oatmeal_cookie_sack
give @s morefood:nether_cookie_sack
give @s morefood:sugar_cookie_sack