give @s morefood:flour_sack
give @s morefood:cornflour_sack
give @s morefood:yeast_sack
give @s morefood:barley_seed_sack
give @s morefood:blueberry_seed_sack
give @s morefood:cabbage_seed_sack
give @s morefood:coffee_bean_sack
give @s morefood:corn_sack
give @s morefood:eggplant_seed_sack
give @s morefood:gherkin_seed_sack
give @s morefood:grape_seed_sack
give @s morefood:hops_seed_sack
give @s morefood:lettuce_seed_sack
give @s morefood:oat_seed_sack
give @s morefood:onion_seed_sack
give @s morefood:peanut_seed_sack
give @s morefood:pepper_seed_sack
give @s morefood:raspberry_seed_sack
give @s morefood:rice_seed_sack
give @s morefood:spinach_seed_sack
give @s morefood:strawberry_seed_sack
give @s morefood:tea_seed_sack
give @s morefood:tomato_seed_sack
give @s morefood:vanilla_seed_sack
give @s morefood:buckwheat_sack
give @s morefood:sweet_potato_sack
give @s morefood:soybean_sack