package com.legopitstop.morefood.registry;

import com.legopitstop.morefood.item.BottledItem;
import com.legopitstop.morefood.item.MealReadyToEatItem;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.item.ItemGroups;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;

public class ModItemGroups {

    public static void register() {
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.NATURAL).register(entries -> {
            entries.add(ModItems.WATERMINT);
            entries.add(ModItems.SPEARMINT);

            entries.addAfter(Items.CHERRY_SAPLING, ModItems.AVOCADO_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, ModItems.ALMOND_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, ModItems.PLUM_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, ModItems.BANANA_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, ModItems.LEMON_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, ModItems.PALM_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, ModItems.OLIVE_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, ModItems.ORANGE_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, ModItems.APPLE_SAPLING);

            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.COFFEE_BEANS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.GHERKIN_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.GRAPE_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.RASPBERRY_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.STRAWBERRY_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.TEA_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.TOMATO_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.VANILLA_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.PEPPER_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.BARLEY_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.CORN);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.HOPS_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.LETTUCE_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.RICE_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.ONION_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.OAT_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.PEANUT_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.BEAN_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.CRANBERRY_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.PEANUT_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.PEPPERMINT_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.ROASTED_SUNFLOWER_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.SPINACH_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.BLUEBERRY_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.CABBAGE_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, ModItems.EGGPLANT_SEEDS);
        });

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.FOOD_AND_DRINK).register(entries -> {
            entries.addAfter(Items.CAKE, ModItems.CHOCOLATE_CAKE);
            entries.addAfter(Items.CAKE, ModItems.RAINBOW_CAKE);
            entries.addAfter(Items.CAKE, ModItems.REDWHITEBLUE_CAKE);
            entries.addAfter(Items.CAKE, ModItems.POUND_CAKE);
            entries.addAfter(Items.CAKE, ModItems.CAKE_WITH_CHERRIES);
            entries.addAfter(Items.COOKIE, ModItems.NETHER_COOKIE);
            entries.addAfter(Items.COOKIE, ModItems.CHOCOLATE_CHUNK_OATMEAL_COOKIE);
            entries.addAfter(Items.COOKIE, ModItems.OATMEAL_COOKIE);
            entries.addAfter(Items.COOKIE, ModItems.SUGAR_COOKIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.PIE_BASE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.APPLE_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.CHEESE_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.CHOCOLATE_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.LEMON_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.STRAWBERRY_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.PLUM_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.TOFFEE_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.BERRY_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.APPLE_RASPBERRY_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.WART_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.CHICKEN_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.PORK_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.STEAK_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.GLOWBERRY_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, ModItems.JALAPENO_CHEESE_PIE);
            entries.addAfter(Items.ENCHANTED_GOLDEN_APPLE, ModItems.NETHERITE_APPLE);
            entries.addAfter(Items.COOKED_SALMON, ModItems.WEDGES);
            entries.addAfter(Items.COOKED_SALMON,ModItems.COOKED_WEDGES);
            entries.addAfter(Items.COOKED_SALMON,ModItems.CHICKEN_NUGGET);
            entries.addAfter(ModItems.CHICKEN_NUGGET, ModItems.COOKED_CHICKEN_NUGGET);
            entries.addAfter(Items.COOKED_SALMON,ModItems.BAT_MEAT);
            entries.addAfter(ModItems.BAT_MEAT, ModItems.COOKED_BAT_MEAT);
            entries.addAfter(Items.COOKED_SALMON,ModItems.HAMBURGER_PATTY);
            entries.addAfter(ModItems.HAMBURGER_PATTY, ModItems.COOKED_HAMBURGER_PATTY);
            entries.addAfter(Items.COOKED_SALMON,ModItems.VEGANBURGER_PATTY);
            entries.addAfter(ModItems.VEGANBURGER_PATTY, ModItems.COOKED_VEGANBURGER_PATTY);
            entries.addAfter(Items.COOKED_SALMON,ModItems.BACON);
            entries.addAfter(ModItems.BACON, ModItems.COOKED_BACON);
            entries.addAfter(Items.COOKED_SALMON,ModItems.HOT_DOG_SAUSAGE);
            entries.addAfter(ModItems.HOT_DOG_SAUSAGE,ModItems.COOKED_HOT_DOG_SAUSAGE);
            entries.addAfter(Items.COOKED_SALMON,ModItems.SAUSAGE);
            entries.addAfter(ModItems.SAUSAGE, ModItems.COOKED_SAUSAGE);
            entries.addAfter(Items.COOKED_SALMON,ModItems.HOGLIN_MEAT);
            entries.addAfter(ModItems.HOGLIN_MEAT, ModItems.COOKED_HOGLIN_MEAT);
            entries.addAfter(Items.COOKED_SALMON,ModItems.SQUID);
            entries.addAfter(ModItems.SQUID, ModItems.FRIED_SQUID);
            entries.addAfter(Items.COOKED_SALMON,ModItems.COOKED_CHICKEN_PIECE);
            entries.addAfter(Items.BREAD, ModItems.CUT_BREAD);
            entries.addAfter(ModItems.CUT_BREAD, ModItems.TOAST);
            entries.addAfter(Items.BREAD, ModItems.SUB_BUN);
            entries.addAfter(Items.BREAD, ModItems.HOT_DOG_BUN);
            entries.addAfter(Items.BREAD, ModItems.TORTILLA);
            entries.addAfter(Items.BREAD, ModItems.MUFFIN_BUN);
            entries.addAfter(Items.BREAD, ModItems.BURGER_BUN);
            entries.addAfter(Items.BREAD, ModItems.PITTA_BREAD);
            entries.addAfter(Items.BREAD, ModItems.PIZZA_BASE);
            entries.addAfter(Items.BREAD, ModItems.BREAD_LOAF);
            entries.add(ModItems.MAPLE_SYRUP_BUCKET);
            entries.add(ModItems.BLUEBERRY_SYRUP);
            entries.add(ModItems.RASPBERRY_SYRUP);
            entries.add(ModItems.STRAWBERRY_SYRUP);
            entries.add(ModItems.MAPLE_SYRUP);
            entries.add(ModItems.MARSHMALLOW);
            entries.add(ModItems.MARSHMALLOW_ON_A_STICK);
            entries.add(ModItems.BURNT_MARSHMALLOW_ON_A_STICK);
            entries.add(ModItems.COOKED_MARSHMALLOW_ON_A_STICK);
            entries.add(Items.EGG);
            entries.add(ModItems.FRIED_EGG);
            entries.add(ModItems.POPCORN);
            entries.add(ModItems.POPCORN_BUCKET);
            entries.add(ModItems.CHOCOLATE_DONUT);
            entries.add(ModItems.COFFEE_DONUT);
            entries.add(ModItems.ICED_DONUT);
            entries.add(ModItems.PINK_ICE_DONUT);
            entries.add(ModItems.PLAIN_DONUT);
            entries.add(ModItems.STRAWBERRY_DONUT);
            entries.add(ModItems.TOFFEE_DONUT);
            entries.add(ModItems.ICE_CREAM_CONE);
            entries.add(ModItems.BANANA_ICE_CREAM);
            entries.add(ModItems.CHOCOLATE_ICE_CREAM);
            entries.add(ModItems.STRAWBERRY_ICE_CREAM);
            entries.add(ModItems.TOFFEE_ICE_CREAM);
            entries.add(ModItems.VANILLA_ICE_CREAM);
            entries.add(ModItems.ICE_CREAM_BOWL);
            entries.add(ModItems.PINK_CUPCAKE);
            entries.add(ModItems.BLUE_CUPCAKE);
            entries.add(ModItems.MILK_CHOCOLATE);
            entries.add(ModItems.WHITE_CHOCOLATE);
            entries.add(ModItems.DARK_CHOCOLATE);
            entries.add(ModItems.ORANGE_JUICE);
            entries.add(ModItems.APPLE_JUICE);
            entries.add(ModItems.GRAPE_JUICE);
            entries.add(ModItems.TOMATO_JUICE);
            entries.add(ModItems.BERRY_JUICE);
            entries.add(ModItems.STRAWBERRY_JUICE);
            entries.add(ModItems.MIXED_FRUIT_JUICE);
            entries.add(ModItems.MELON_JUICE);
            entries.add(ModItems.LEMON_JUICE);
            entries.add(ModItems.GLOWBERRY_JUICE);
            entries.add(ModItems.APPLE_ICECRUSH);
            entries.add(ModItems.BERRY_ICECRUSH);
            entries.add(ModItems.GRAPE_ICECRUSH);
            entries.add(ModItems.LEMON_ICECRUSH);
            entries.add(ModItems.MELON_ICECRUSH);
            entries.add(ModItems.MIXED_FRUIT_ICECRUSH);
            entries.add(ModItems.ORANGE_ICECRUSH);
            entries.add(ModItems.STRAWBERRY_ICECRUSH);
            entries.add(ModItems.APPLE_RASPBERRY_ICECRUSH);
            entries.add(ModItems.GLOWBERRY_ICECRUSH);
            entries.add(ModItems.BANANA_SMOOTHIE);
            entries.add(ModItems.BERRY_SMOOTHIE);
            entries.add(ModItems.GRAPE_SMOOTHIE);
            entries.add(ModItems.STRAWBERRY_SMOOTHIE);
            entries.add(ModItems.RASPBERRY_SMOOTHIE);
            entries.add(ModItems.MIXED_FRUIT_SMOOTHIE);
            entries.add(ModItems.GLOWBERRY_SMOOTHIE);
            entries.add(ModItems.CHOCOLATE_MILKSHAKE);
            entries.add(ModItems.STRAWBERRY_MILKSHAKE);
            entries.add(ModItems.BANANA_MILKSHAKE);
            entries.add(ModItems.APPLE_SODA);
            entries.add(ModItems.BERRY_SODA);
            entries.add(ModItems.GRAPE_SODA);
            entries.add(ModItems.LEMON_SODA);
            entries.add(ModItems.ORANGE_SODA);
            entries.add(ModItems.STRAWBERRY_SODA);
            entries.add(ModItems.GLOWBERRY_SODA);
            entries.add(ModItems.VANILLA_PUDDING);
            entries.add(ModItems.RICE_PUDDING);
            entries.add(ModItems.CHOCOLATE_PUDDING);
            entries.add(ModItems.DARK_CHOCOLATE_COVERED_APPLE);
            entries.add(ModItems.MILK_CHOCOLATE_COVERED_APPLE);
            entries.add(ModItems.WHITE_CHOCOLATE_COVERED_APPLE);
            entries.add(ModItems.CHOCOLATE_PROTEIN_DRINK);
            entries.add(ModItems.COCOA_BEVERAGE);
            entries.add(ModItems.GRAPE_BEVERAGE);
            entries.add(ModItems.LEMON_LIME_BEVERAGE);
            entries.add(ModItems.ORANGE_BEVERAGE);
            entries.add(ModItems.ORANGE_BEVERAGE);
            entries.add(ModItems.TROPICAL_PUNCH_BEVERAGE);
            entries.add(ModItems.BREADSTICKS);
            entries.add(ModItems.BREADSTICKS_WITH_GLOWBERRY_JAM);
            entries.add(ModItems.BREADSTICKS_WITH_JAM);
            entries.add(ModItems.BREADSTICKS_WITH_PEANUT_BUTTER);
            entries.add(ModItems.CRACKERS);
            entries.add(ModItems.CRACKERS_WITH_CHEESE);
            entries.add(ModItems.CRACKERS_WITH_CHOCOLATE_PEANUT_BUTTER);
            entries.add(ModItems.CRACKERS_WITH_GLOWBERRY_JAM);
            entries.add(ModItems.CRACKERS_WITH_JALAPENO_CHEESE);
            entries.add(ModItems.CRACKERS_WITH_JAM);
            entries.add(ModItems.CRACKERS_WITH_PEANUT_BUTTER);
            entries.add(ModItems.CUT_BREAD_WITH_CHEESE);
            entries.add(ModItems.CUT_BREAD_WITH_CHOCOLATE_PEANUT_BUTTER);
            entries.add(ModItems.CUT_BREAD_WITH_GLOWBERRY_JAM);
            entries.add(ModItems.CUT_BREAD_WITH_JALAPENO_CHEESE);
            entries.add(ModItems.CUT_BREAD_WITH_JAM);
            entries.add(ModItems.CUT_BREAD_WITH_PEANUT_BUTTER);
            entries.add(ModItems.PULLED_BEEF_BURGER);
            entries.add(ModItems.PORK_SAUSAGE_BURGER);
            entries.add(ModItems.JAM);
            entries.add(ModItems.GLOWBERRY_JAM);
            entries.add(ModItems.JALAPENO_CHEESE_TOASTIE);
            entries.add(ModItems.CHEESE_TOASTIE);
            entries.add(ModItems.JELLY_SANDWICH);
            entries.add(ModItems.GLOWBERRY_JELLY_SANDWICH);
            entries.add(ModItems.BACON_EGG_SANDWICH);
            entries.add(ModItems.SAUSAGE_EGG_SANDWICH);
            entries.add(ModItems.PEANUT_BUTTER_JELLY_SANDWICH);
            entries.add(ModItems.PEANUT_BUTTER_JELLY_SANDWICH);
            entries.add(ModItems.TUNA_SANDWICH);
            entries.add(ModItems.BACON_EGG_MUFFIN);
            entries.add(ModItems.SAUSAGE_EGG_MUFFIN);
            entries.add(ModItems.STRAWBERRY_JELLY);
            entries.add(ModItems.ORANGE_JELLY);
            entries.add(ModItems.WEDGES_POT);
            entries.add(ModItems.RICE);
            entries.add(ModItems.HAMBURGER);
            entries.add(ModItems.VEGANBURGER);
            entries.add(ModItems.ROUND_CHEESE);
            entries.add(ModItems.ORANGE);
            entries.add(ModItems.GRAPE);
            entries.add(ModItems.TOMATO);
            entries.add(ModItems.BANANA);
            entries.add(ModItems.LEMON);
            entries.add(ModItems.STRAWBERRY);
            entries.add(ModItems.TEA_LEAVES);
            entries.add(ModItems.PLUM);
            entries.add(ModItems.OLIVES);
            entries.add(ModItems.RASPBERRY);
            entries.add(ModItems.CUT_FRIES);
            entries.add(ModItems.FRIES);
            entries.add(ModItems.CORN_COB);
            entries.add(ModItems.DOUGH);
            entries.add(ModItems.LETTUCE);
            entries.add(ModItems.HOPS);
            entries.add(ModItems.VANILLA_POD);
            entries.add(ModItems.YEAST);
            entries.add(ModItems.TOMATO_PUREE);
            entries.add(ModItems.GHERKIN);
            entries.add(ModItems.PEPPER);
            entries.add(ModItems.CHICKEN_SELECT);
            entries.add(ModItems.TOFFEE);
            entries.add(ModItems.SUSHI);
            entries.add(ModItems.ONIGIRI);
            entries.add(ModItems.SASHIMI);
            entries.add(ModItems.BEEF_SUB);
            entries.add(ModItems.CHEESE_WEDGE);
            entries.add(ModItems.TURKISH_DELIGHT);
            entries.add(ModItems.WAFFLE);
            entries.add(ModItems.PANCAKES);
            entries.add(ModItems.PICKLES);
            entries.add(ModItems.WARPED_BERRIES);
            entries.add(ModItems.PIZZA_SLICE);
            entries.add(ModItems.PIZZA);
            entries.add(ModItems.HOT_DOG);
            entries.add(ModItems.TACO);
            entries.add(ModItems.CHICKEN_FAJITA);
            entries.add(ModItems.BURRITO);
            entries.add(ModItems.KEBAB);
            entries.add(ModItems.BREAKFAST_SUB);
            entries.add(ModItems.BUTTER);
            entries.add(ModItems.SHROOMLIGHT_SLICES);
            entries.add(ModItems.ONION);
            entries.add(ModItems.COCONUT_MEAT);
            entries.add(ModItems.CHICKEN_SUB);
            entries.add(ModItems.ROTTEN_PORKCHOP);
            entries.add(ModItems.CEREAL);
            entries.add(ModItems.FUNGUS_STEW);
            entries.add(ModItems.SPAGHETTI);
            entries.add(ModItems.RAMEN_NOODLES);
            entries.add(ModItems.CUSTARD);
            entries.add(ModItems.NETHERWART_CHICKEN_SOUP);
            entries.add(ModItems.NETHERWART_MUSHROOM_SOUP);
            entries.add(ModItems.AMERICANO);
            entries.add(ModItems.CAPPUCCINO);
            entries.add(ModItems.MACCHIATO);
            entries.add(ModItems.MOCHA);
            entries.add(ModItems.TOFFEE_LATTE);
            entries.add(ModItems.VANILLA_LATTE);
            entries.add(ModItems.HOT_COFFEE);
            entries.add(ModItems.HOT_TEA);
            entries.add(ModItems.HOT_COCOA);
            entries.add(ModItems.VANILLA_EXTRACT);
            entries.add(ModItems.KETCHUP);
            entries.add(ModItems.COCONUT_MILK);
            entries.add(ModItems.SPARKLING_WATER_BOTTLE);
            entries.add(ModItems.CIDER);
            entries.add(ModItems.RED_WINE);
            entries.add(ModItems.WHITE_WINE);
            entries.add(ModItems.BEER);
            entries.add(ModItems.CREATIVE_HUNGER);
            entries.add(ModItems.MILK_CARTON);
            entries.add(ModItems.CREAM_CARTON);
            entries.add(ModItems.APPLESAUCE);
            entries.add(ModItems.BAKED_SWEET_POTATO);
            entries.add(ModItems.BEANS);
            entries.add(ModItems.BEEF_GOULASH);
            entries.add(ModItems.BEEF_RAVIOLI);
            entries.add(ModItems.BEEF_STEW);
            entries.add(ModItems.BUCKWHEAT);
            entries.add(ModItems.CHEESE_SPREAD);
            entries.add(ModItems.CHEESE_TORTELLINI);
            entries.add(ModItems.CHICKEN_SOUP);
            entries.add(ModItems.CHILI);
            entries.add(ModItems.CHOCOLATE_BANANA_MUFFIN);
            entries.add(ModItems.CHOCOLATE_PEANUT_BUTTER);
            entries.add(ModItems.CORNBREAD);
            entries.add(ModItems.CRANBERRIES);
            entries.add(ModItems.CUT_SWEET_POTATO);
            entries.add(ModItems.DRIED_CRANBERRIES);
            entries.add(ModItems.DRIED_RAISENS);
            entries.add(ModItems.GARLIC_MASHED_POTATOES);
            entries.add(ModItems.GUACAMOLE);
            entries.add(ModItems.HASH_BROWNS);
            entries.add(ModItems.JALAPENO_CHEESE_BUCKET);
            entries.add(ModItems.JALAPENO_CHEESE_SPREAD);
            entries.add(ModItems.JALAPENO_CHEESE_WEDGE);
            entries.add(ModItems.JALAPENO_ROUND_CHEESE);
            entries.add(ModItems.MAPLE_MUFFIN);
            entries.add(ModItems.MAPLE_SAP_BUCKET);
            entries.add(ModItems.MASHED_POTATOES);
            entries.add(ModItems.OATMEAL);
            entries.add(ModItems.ONION_RINGS);
            entries.add(ModItems.PEANUT_BUTTER);
            entries.add(ModItems.PEPPERMINT_RING);
            entries.add(ModItems.SWEET_POTATO);
            entries.add(ModItems.ALMONDS);
            entries.add(ModItems.AVOCADO);
            entries.add(ModItems.BLUEBERRIES);
            entries.add(ModItems.CABBAGE);
            entries.add(ModItems.CHERRIES);
            entries.add(ModItems.EGGPLANT);
            entries.add(ModItems.GARLIC);
            entries.add(ModItems.GARLIC_BULB);
            entries.add(ModItems.OATS);
            entries.add(ModItems.PEANUT);
            entries.add(ModItems.PEPPERMINT);
            entries.add(ModItems.PEPPERMINT_EXTRACT);
            entries.add(ModItems.PEPPERMINT_RING);
            entries.add(ModItems.POISONOUS_SWEET_POTATO);
            entries.add(ModItems.POISON_BERRIES);
            entries.add(ModItems.PRETZEL);
            entries.add(ModItems.PRETZEL_NUGGETS);
            entries.add(ModItems.PRETZEL_STICKS);
            entries.add(ModItems.ROASTED_PEANUT);
            entries.add(ModItems.ROASTED_SOYBEANS);
            entries.add(ModItems.SMOKED_ALMONDS);
            entries.add(ModItems.SOYBEANS);
            entries.add(ModItems.SPAGHETTI_WITH_MEATBALLS);
            entries.add(ModItems.SPINACH);
            entries.add(ModItems.SPINACH_FETTUCCINE);
            entries.add(ModItems.SWEET_MASHED_POTATOES);
            entries.add(ModItems.SWEET_POTATO_FRIES);
            entries.add(ModItems.TORTILLA_CHIPS);
            entries.add(ModItems.TORTILLA_WITH_CHEESE);
            entries.add(ModItems.TORTILLA_WITH_JALAPENO_CHEESE);
            entries.add(ModItems.TRAIL_MIX);
        });

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.COMBAT).register(entries -> {
            entries.add(ModItems.WOODEN_KNIFE);
            entries.addAfter(ModItems.WOODEN_KNIFE, ModItems.STONE_KNIFE);
            entries.addAfter(ModItems.STONE_KNIFE, ModItems.IRON_KNIFE);
            entries.addAfter(ModItems.IRON_KNIFE, ModItems.GOLDEN_KNIFE);
            entries.addAfter(ModItems.GOLDEN_KNIFE, ModItems.COPPER_KNIFE);
            entries.addAfter(ModItems.COPPER_KNIFE, ModItems.DIAMOND_KNIFE);
            entries.addAfter(ModItems.DIAMOND_KNIFE, ModItems.NETHERITE_KNIFE);
        });

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.TOOLS).register(entries -> {
            entries.add(ModItems.WOODEN_SPOON);
        });

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.INGREDIENTS).register(entries -> {
            entries.add(ModItems.CHOCOLATE_PROTEIN_DRINK_MIX);
            entries.add(ModItems.CAPPUCCINO_DRINK_MIX);
            entries.add(ModItems.TROPICAL_PUNCH_BEVERAGE_POWDER);
            entries.add(ModItems.COCOA_BEVERAGE_POWDER);
            entries.add(ModItems.ORANGE_BEVERAGE_POWDER);
            entries.add(ModItems.ORANGE_BEVERAGE_POWDER);
            entries.add(ModItems.GRAPE_BEVERAGE_POWDER);
            entries.add(ModItems.LEMON_LIME_BEVERAGE_POWDER);

            entries.add(BottledItem.addUses(new ItemStack(ModItems.BOTTLED_BEER), 4));
            entries.add(BottledItem.addUses(new ItemStack(ModItems.BOTTLED_CIDER), 4));
            entries.add(BottledItem.addUses(new ItemStack(ModItems.BOTTLED_RED_WINE), 4));
            entries.add(BottledItem.addUses(new ItemStack(ModItems.BOTTLED_WHITE_WINE), 4));

            entries.add(ModItems.LARGE_BOWL);
            entries.add(ModItems.PANCAKE_MIX);
            entries.add(ModItems.GLASS_SHARD);
            entries.add(ModItems.PULP);
            entries.add(ModItems.WOODEN_TREE_TAP);
            entries.add(ModItems.CHEESE_BUCKET);
            entries.add(ModItems.OIL);
            entries.add(ModItems.BEER_GLASS);
            entries.add(ModItems.CORN_FLOUR);
            entries.add(ModItems.FLOUR);
            entries.add(ModItems.BEVERAGE_CUP);
            entries.add(ModItems.BOTTLE);
            entries.add(ModItems.CARTON);
            entries.add(ModItems.CHICKEN_SELECT_BOX);
            entries.add(ModItems.ICECRUSH_GLASS);
            entries.add(ModItems.TUMBLER_GLASS);
            entries.add(ModItems.FRY_WRAPPER);
            entries.add(ModItems.HOT_BEVERAGE_CUP);
            entries.add(ModItems.ICING);
            entries.add(ModItems.JAR);
            entries.add(ModItems.SODA_CAN);
            entries.add(ModItems.STARCH);
            entries.add(ModItems.WINE_GLASS);
            entries.add(ModItems.SUB_WRAPPER);
            entries.add(ModItems.SALT);
            entries.add(ModItems.NOODLES);
            entries.add(ModItems.PASTA);
            entries.add(ModItems.COCONUT);
            entries.add(ModItems.SPARKLING_WATER_BUCKET);
            entries.add(ModItems.GELATIN);

            entries.add(MealReadyToEatItem.addNbtLootTable(new ItemStack(ModItems.MEAL_READY_TO_EAT), "morefood:mre/default"));
        });

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.BUILDING_BLOCKS).register(entries -> {
            entries.add(ModItems.CHERRY_SACK);
            entries.add(ModItems.ALMOND_SACK);
            entries.add(ModItems.AVOCADO_SACK);
            entries.add(ModItems.BANANA_SACK);
            entries.add(ModItems.BARLEY_SEED_SACK);
            entries.add(ModItems.BEAN_SACK);
            entries.add(ModItems.BLUEBERRY_SACK);
            entries.add(ModItems.BLUEBERRY_SEED_SACK);
            entries.add(ModItems.BUCKWHEAT_SACK);
            entries.add(ModItems.CABBAGE_SACK);
            entries.add(ModItems.CABBAGE_SEED_SACK);
            entries.add(ModItems.CHOCOLATE_CHUNK_OATMEAL_COOKIE_SACK);
            entries.add(ModItems.COCONUT_SACK);
            entries.add(ModItems.COFFEE_BEAN_SACK);
            entries.add(ModItems.CORN_FLOUR_SACK);
            entries.add(ModItems.CORN_COB_SACK);
            entries.add(ModItems.CORN_SACK);
            entries.add(ModItems.CRANBERRY_SACK);
            entries.add(ModItems.EGGPLANT_SACK);
            entries.add(ModItems.EGGPLANT_SEED_SACK);
            entries.add(ModItems.FLOUR_SACK);
            entries.add(ModItems.GARLIC_SACK);
            entries.add(ModItems.GHERKIN_SACK);
            entries.add(ModItems.GHERKIN_SEED_SACK);
            entries.add(ModItems.GRAPE_SACK);
            entries.add(ModItems.GRAPE_SEED_SACK);
            entries.add(ModItems.HOPS_SACK);
            entries.add(ModItems.HOPS_SEED_SACK);
            entries.add(ModItems.LEMON_SACK);
            entries.add(ModItems.LETTUCE_SACK);
            entries.add(ModItems.LETTUCE_SEED_SACK);
            entries.add(ModItems.NETHER_COOKIE_SACK);
            entries.add(ModItems.OATMEAL_COOKIE_SACK);
            entries.add(ModItems.OAT_SACK);
            entries.add(ModItems.OAT_SEED_SACK);
            entries.add(ModItems.OLIVES_SACK);
            entries.add(ModItems.ONION_SACK);
            entries.add(ModItems.ONION_SEED_SACK);
            entries.add(ModItems.ORANGE_SACK);
            entries.add(ModItems.PEANUT_SACK);
            entries.add(ModItems.PEANUT_SEED_SACK);
            entries.add(ModItems.PEPPER_SACK);
            entries.add(ModItems.PEPPER_SEED_SACK);
            entries.add(ModItems.PLUM_SACK);
            entries.add(ModItems.POISONOUS_SWEET_POTATO_SACK);
            entries.add(ModItems.POISON_BERRY_SACK);
            entries.add(ModItems.RASPBERRY_SACK);
            entries.add(ModItems.RASPBERRY_SEED_SACK);
            entries.add(ModItems.RICE_SACK);
            entries.add(ModItems.RICE_SEED_SACK);
            entries.add(ModItems.SOYBEAN_SACK);
            entries.add(ModItems.SPINACH_SACK);
            entries.add(ModItems.SPINACH_SEED_SACK);
            entries.add(ModItems.STRAWBERRY_SACK);
            entries.add(ModItems.STRAWBERRY_SEED_SACK);
            entries.add(ModItems.SUGAR_COOKIE_SACK);
            entries.add(ModItems.SWEET_POTATO_SACK);
            entries.add(ModItems.TEA_LEAF_SACK);
            entries.add(ModItems.TEA_SEED_SACK);
            entries.add(ModItems.TOMATO_SACK);
            entries.add(ModItems.TOMATO_SEED_SACK);
            entries.add(ModItems.VANILLA_POD_SACK);
            entries.add(ModItems.VANILLA_SEED_SACK);
            entries.add(ModItems.YEAST_SACK);
        });
    }
}
