package com.legopitstop.morefood.registry;

import com.legopitstop.morefood.MoreFood;
import com.legopitstop.morefood.item.BottledItem;
import com.legopitstop.morefood.item.MealReadyToEatItem;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.Block;
import net.minecraft.item.ItemGroups;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.util.Identifier;

public class MoreFoodItemGroups {

    public static void register() {
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.COLORED_BLOCKS).register(entries -> {
            entries.add(MoreFoodItems.WHITE_CANDY);
            entries.add(MoreFoodItems.LIGHT_GRAY_CANDY);
            entries.add(MoreFoodItems.GRAY_CANDY);
            entries.add(MoreFoodItems.BLACK_CANDY);
            entries.add(MoreFoodItems.BROWN_CANDY);
            entries.add(MoreFoodItems.RED_CANDY);
            entries.add(MoreFoodItems.ORANGE_CANDY);
            entries.add(MoreFoodItems.YELLOW_CANDY);
            entries.add(MoreFoodItems.LIME_CANDY);
            entries.add(MoreFoodItems.GREEN_CANDY);
            entries.add(MoreFoodItems.CYAN_CANDY);
            entries.add(MoreFoodItems.LIGHT_BLUE_CANDY);
            entries.add(MoreFoodItems.BLUE_CANDY);
            entries.add(MoreFoodItems.PURPLE_CANDY);
            entries.add(MoreFoodItems.MAGENTA_CANDY);
            entries.add(MoreFoodItems.PINK_CANDY);
        });

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.NATURAL).register(entries -> {
            entries.addAfter(Items.FERN, MoreFoodItems.WATERMINT);
            entries.addAfter(Items.FERN, MoreFoodItems.SPEARMINT);

            entries.addAfter(Items.CHERRY_SAPLING, MoreFoodItems.AVOCADO_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, MoreFoodItems.ALMOND_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, MoreFoodItems.PLUM_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, MoreFoodItems.BANANA_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, MoreFoodItems.LEMON_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, MoreFoodItems.PALM_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, MoreFoodItems.OLIVE_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, MoreFoodItems.ORANGE_SAPLING);
            entries.addAfter(Items.CHERRY_SAPLING, MoreFoodItems.APPLE_SAPLING);

            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.COFFEE_BEANS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.GHERKIN_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.GRAPE_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.RASPBERRY_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.STRAWBERRY_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.TEA_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.TOMATO_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.VANILLA_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.PEPPER_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.BARLEY_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.CORN);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.HOPS_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.LETTUCE_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.RICE_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.ONION_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.OAT_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.PEANUT_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.BEAN_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.CRANBERRY_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.PEANUT_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.PEPPERMINT_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.ROASTED_SUNFLOWER_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.SPINACH_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.BLUEBERRY_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.CABBAGE_SEEDS);
            entries.addAfter(Items.BEETROOT_SEEDS, MoreFoodItems.EGGPLANT_SEEDS);
        });

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.FOOD_AND_DRINK).register(entries -> {
            entries.addAfter(Items.CAKE, MoreFoodItems.CHOCOLATE_CAKE);
            entries.addAfter(Items.CAKE, MoreFoodItems.RAINBOW_CAKE);
            entries.addAfter(Items.CAKE, MoreFoodItems.REDWHITEBLUE_CAKE);
            entries.addAfter(Items.CAKE, MoreFoodItems.POUND_CAKE);
            entries.addAfter(Items.CAKE, MoreFoodItems.CAKE_WITH_CHERRIES);
            entries.addAfter(Items.COOKIE, MoreFoodItems.NETHER_COOKIE);
            entries.addAfter(Items.COOKIE, MoreFoodItems.CHOCOLATE_CHUNK_OATMEAL_COOKIE);
            entries.addAfter(Items.COOKIE, MoreFoodItems.OATMEAL_COOKIE);
            entries.addAfter(Items.COOKIE, MoreFoodItems.SUGAR_COOKIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.PIE_BASE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.APPLE_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.CHEESE_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.CHOCOLATE_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.LEMON_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.STRAWBERRY_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.PLUM_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.TOFFEE_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.BERRY_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.APPLE_RASPBERRY_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.WART_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.CHICKEN_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.PORK_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.STEAK_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.GLOWBERRY_PIE);
            entries.addAfter(Items.PUMPKIN_PIE, MoreFoodItems.JALAPENO_CHEESE_PIE);
            entries.addAfter(Items.ENCHANTED_GOLDEN_APPLE, MoreFoodItems.NETHERITE_APPLE);
            entries.addAfter(Items.COOKED_SALMON, MoreFoodItems.WEDGES);
            entries.addAfter(Items.COOKED_SALMON, MoreFoodItems.COOKED_WEDGES);
            entries.addAfter(Items.COOKED_SALMON, MoreFoodItems.CHICKEN_NUGGET);
            entries.addAfter(MoreFoodItems.CHICKEN_NUGGET, MoreFoodItems.COOKED_CHICKEN_NUGGET);
            entries.addAfter(Items.COOKED_SALMON, MoreFoodItems.BAT_MEAT);
            entries.addAfter(MoreFoodItems.BAT_MEAT, MoreFoodItems.COOKED_BAT_MEAT);
            entries.addAfter(Items.COOKED_SALMON, MoreFoodItems.HAMBURGER_PATTY);
            entries.addAfter(MoreFoodItems.HAMBURGER_PATTY, MoreFoodItems.COOKED_HAMBURGER_PATTY);
            entries.addAfter(Items.COOKED_SALMON, MoreFoodItems.VEGANBURGER_PATTY);
            entries.addAfter(MoreFoodItems.VEGANBURGER_PATTY, MoreFoodItems.COOKED_VEGANBURGER_PATTY);
            entries.addAfter(Items.COOKED_SALMON, MoreFoodItems.BACON);
            entries.addAfter(MoreFoodItems.BACON, MoreFoodItems.COOKED_BACON);
            entries.addAfter(Items.COOKED_SALMON, MoreFoodItems.HOT_DOG_SAUSAGE);
            entries.addAfter(MoreFoodItems.HOT_DOG_SAUSAGE, MoreFoodItems.COOKED_HOT_DOG_SAUSAGE);
            entries.addAfter(Items.COOKED_SALMON, MoreFoodItems.SAUSAGE);
            entries.addAfter(MoreFoodItems.SAUSAGE, MoreFoodItems.COOKED_SAUSAGE);
            entries.addAfter(Items.COOKED_SALMON, MoreFoodItems.HOGLIN_MEAT);
            entries.addAfter(MoreFoodItems.HOGLIN_MEAT, MoreFoodItems.COOKED_HOGLIN_MEAT);
            entries.addAfter(Items.COOKED_SALMON, MoreFoodItems.SQUID);
            entries.addAfter(MoreFoodItems.SQUID, MoreFoodItems.FRIED_SQUID);
            entries.addAfter(Items.COOKED_SALMON, MoreFoodItems.COOKED_CHICKEN_PIECE);
            entries.addAfter(Items.BREAD, MoreFoodItems.CUT_BREAD);
            entries.addAfter(MoreFoodItems.CUT_BREAD, MoreFoodItems.TOAST);
            entries.addAfter(Items.BREAD, MoreFoodItems.SUB_BUN);
            entries.addAfter(Items.BREAD, MoreFoodItems.HOT_DOG_BUN);
            entries.addAfter(Items.BREAD, MoreFoodItems.TORTILLA);
            entries.addAfter(Items.BREAD, MoreFoodItems.MUFFIN_BUN);
            entries.addAfter(Items.BREAD, MoreFoodItems.BURGER_BUN);
            entries.addAfter(Items.BREAD, MoreFoodItems.PITTA_BREAD);
            entries.addAfter(Items.BREAD, MoreFoodItems.PIZZA_BASE);
            entries.addAfter(Items.BREAD, MoreFoodItems.BREAD_LOAF);
            entries.add(MoreFoodItems.MAPLE_SYRUP_BUCKET);
            entries.add(MoreFoodItems.BLUEBERRY_SYRUP);
            entries.add(MoreFoodItems.RASPBERRY_SYRUP);
            entries.add(MoreFoodItems.STRAWBERRY_SYRUP);
            entries.add(MoreFoodItems.MAPLE_SYRUP);
            entries.add(MoreFoodItems.MARSHMALLOW);
            entries.add(MoreFoodItems.MARSHMALLOW_ON_A_STICK);
            entries.add(MoreFoodItems.BURNT_MARSHMALLOW_ON_A_STICK);
            entries.add(MoreFoodItems.COOKED_MARSHMALLOW_ON_A_STICK);
            entries.add(Items.EGG);
            entries.add(MoreFoodItems.FRIED_EGG);
            entries.add(MoreFoodItems.POPCORN);
            entries.add(MoreFoodItems.POPCORN_BUCKET);
            entries.add(MoreFoodItems.CHOCOLATE_DONUT);
            entries.add(MoreFoodItems.COFFEE_DONUT);
            entries.add(MoreFoodItems.ICED_DONUT);
            entries.add(MoreFoodItems.PINK_ICE_DONUT);
            entries.add(MoreFoodItems.PLAIN_DONUT);
            entries.add(MoreFoodItems.STRAWBERRY_DONUT);
            entries.add(MoreFoodItems.TOFFEE_DONUT);
            entries.add(MoreFoodItems.ICE_CREAM_CONE);
            entries.add(MoreFoodItems.BANANA_ICE_CREAM);
            entries.add(MoreFoodItems.CHOCOLATE_ICE_CREAM);
            entries.add(MoreFoodItems.STRAWBERRY_ICE_CREAM);
            entries.add(MoreFoodItems.TOFFEE_ICE_CREAM);
            entries.add(MoreFoodItems.VANILLA_ICE_CREAM);
            entries.add(MoreFoodItems.ICE_CREAM_BOWL);
            entries.add(MoreFoodItems.PINK_CUPCAKE);
            entries.add(MoreFoodItems.BLUE_CUPCAKE);
            entries.add(MoreFoodItems.MILK_CHOCOLATE);
            entries.add(MoreFoodItems.WHITE_CHOCOLATE);
            entries.add(MoreFoodItems.DARK_CHOCOLATE);
            entries.add(MoreFoodItems.ORANGE_JUICE);
            entries.add(MoreFoodItems.APPLE_JUICE);
            entries.add(MoreFoodItems.GRAPE_JUICE);
            entries.add(MoreFoodItems.TOMATO_JUICE);
            entries.add(MoreFoodItems.BERRY_JUICE);
            entries.add(MoreFoodItems.STRAWBERRY_JUICE);
            entries.add(MoreFoodItems.MIXED_FRUIT_JUICE);
            entries.add(MoreFoodItems.MELON_JUICE);
            entries.add(MoreFoodItems.LEMON_JUICE);
            entries.add(MoreFoodItems.GLOWBERRY_JUICE);
            entries.add(MoreFoodItems.APPLE_ICECRUSH);
            entries.add(MoreFoodItems.BERRY_ICECRUSH);
            entries.add(MoreFoodItems.GRAPE_ICECRUSH);
            entries.add(MoreFoodItems.LEMON_ICECRUSH);
            entries.add(MoreFoodItems.MELON_ICECRUSH);
            entries.add(MoreFoodItems.MIXED_FRUIT_ICECRUSH);
            entries.add(MoreFoodItems.ORANGE_ICECRUSH);
            entries.add(MoreFoodItems.STRAWBERRY_ICECRUSH);
            entries.add(MoreFoodItems.APPLE_RASPBERRY_ICECRUSH);
            entries.add(MoreFoodItems.GLOWBERRY_ICECRUSH);
            entries.add(MoreFoodItems.BANANA_SMOOTHIE);
            entries.add(MoreFoodItems.BERRY_SMOOTHIE);
            entries.add(MoreFoodItems.GRAPE_SMOOTHIE);
            entries.add(MoreFoodItems.STRAWBERRY_SMOOTHIE);
            entries.add(MoreFoodItems.RASPBERRY_SMOOTHIE);
            entries.add(MoreFoodItems.MIXED_FRUIT_SMOOTHIE);
            entries.add(MoreFoodItems.GLOWBERRY_SMOOTHIE);
            entries.add(MoreFoodItems.CHOCOLATE_MILKSHAKE);
            entries.add(MoreFoodItems.STRAWBERRY_MILKSHAKE);
            entries.add(MoreFoodItems.BANANA_MILKSHAKE);
            entries.add(MoreFoodItems.APPLE_SODA);
            entries.add(MoreFoodItems.BERRY_SODA);
            entries.add(MoreFoodItems.GRAPE_SODA);
            entries.add(MoreFoodItems.LEMON_SODA);
            entries.add(MoreFoodItems.ORANGE_SODA);
            entries.add(MoreFoodItems.STRAWBERRY_SODA);
            entries.add(MoreFoodItems.GLOWBERRY_SODA);
            entries.add(MoreFoodItems.VANILLA_PUDDING);
            entries.add(MoreFoodItems.RICE_PUDDING);
            entries.add(MoreFoodItems.CHOCOLATE_PUDDING);
            entries.add(MoreFoodItems.DARK_CHOCOLATE_COVERED_APPLE);
            entries.add(MoreFoodItems.MILK_CHOCOLATE_COVERED_APPLE);
            entries.add(MoreFoodItems.WHITE_CHOCOLATE_COVERED_APPLE);
            entries.add(MoreFoodItems.CHOCOLATE_PROTEIN_DRINK);
            entries.add(MoreFoodItems.COCOA_BEVERAGE);
            entries.add(MoreFoodItems.GRAPE_BEVERAGE);
            entries.add(MoreFoodItems.LEMON_LIME_BEVERAGE);
            entries.add(MoreFoodItems.ORANGE_BEVERAGE);
            entries.add(MoreFoodItems.ORANGE_BEVERAGE);
            entries.add(MoreFoodItems.TROPICAL_PUNCH_BEVERAGE);
            entries.add(MoreFoodItems.BREADSTICKS);
            entries.add(MoreFoodItems.BREADSTICKS_WITH_GLOWBERRY_JAM);
            entries.add(MoreFoodItems.BREADSTICKS_WITH_JAM);
            entries.add(MoreFoodItems.BREADSTICKS_WITH_PEANUT_BUTTER);
            entries.add(MoreFoodItems.CRACKERS);
            entries.add(MoreFoodItems.CRACKERS_WITH_CHEESE);
            entries.add(MoreFoodItems.CRACKERS_WITH_CHOCOLATE_PEANUT_BUTTER);
            entries.add(MoreFoodItems.CRACKERS_WITH_GLOWBERRY_JAM);
            entries.add(MoreFoodItems.CRACKERS_WITH_JALAPENO_CHEESE);
            entries.add(MoreFoodItems.CRACKERS_WITH_JAM);
            entries.add(MoreFoodItems.CRACKERS_WITH_PEANUT_BUTTER);
            entries.add(MoreFoodItems.CUT_BREAD_WITH_CHEESE);
            entries.add(MoreFoodItems.CUT_BREAD_WITH_CHOCOLATE_PEANUT_BUTTER);
            entries.add(MoreFoodItems.CUT_BREAD_WITH_GLOWBERRY_JAM);
            entries.add(MoreFoodItems.CUT_BREAD_WITH_JALAPENO_CHEESE);
            entries.add(MoreFoodItems.CUT_BREAD_WITH_JAM);
            entries.add(MoreFoodItems.CUT_BREAD_WITH_PEANUT_BUTTER);
            entries.add(MoreFoodItems.PULLED_BEEF_BURGER);
            entries.add(MoreFoodItems.PORK_SAUSAGE_BURGER);
            entries.add(MoreFoodItems.JAM);
            entries.add(MoreFoodItems.GLOWBERRY_JAM);
            entries.add(MoreFoodItems.JALAPENO_CHEESE_TOASTIE);
            entries.add(MoreFoodItems.CHEESE_TOASTIE);
            entries.add(MoreFoodItems.JELLY_SANDWICH);
            entries.add(MoreFoodItems.GLOWBERRY_JELLY_SANDWICH);
            entries.add(MoreFoodItems.BACON_EGG_SANDWICH);
            entries.add(MoreFoodItems.SAUSAGE_EGG_SANDWICH);
            entries.add(MoreFoodItems.PEANUT_BUTTER_JELLY_SANDWICH);
            entries.add(MoreFoodItems.PEANUT_BUTTER_JELLY_SANDWICH);
            entries.add(MoreFoodItems.TUNA_SANDWICH);
            entries.add(MoreFoodItems.BACON_EGG_MUFFIN);
            entries.add(MoreFoodItems.SAUSAGE_EGG_MUFFIN);
            entries.add(MoreFoodItems.STRAWBERRY_JELLY);
            entries.add(MoreFoodItems.ORANGE_JELLY);
            entries.add(MoreFoodItems.WEDGES_POT);
            entries.add(MoreFoodItems.RICE);
            entries.add(MoreFoodItems.HAMBURGER);
            entries.add(MoreFoodItems.VEGANBURGER);
            entries.add(MoreFoodItems.ROUND_CHEESE);
            entries.add(MoreFoodItems.ORANGE);
            entries.add(MoreFoodItems.GRAPE);
            entries.add(MoreFoodItems.TOMATO);
            entries.add(MoreFoodItems.BANANA);
            entries.add(MoreFoodItems.LEMON);
            entries.add(MoreFoodItems.STRAWBERRY);
            entries.add(MoreFoodItems.TEA_LEAVES);
            entries.add(MoreFoodItems.PLUM);
            entries.add(MoreFoodItems.OLIVES);
            entries.add(MoreFoodItems.RASPBERRY);
            entries.add(MoreFoodItems.CUT_FRIES);
            entries.add(MoreFoodItems.FRIES);
            entries.add(MoreFoodItems.CORN_COB);
            entries.add(MoreFoodItems.DOUGH);
            entries.add(MoreFoodItems.LETTUCE);
            entries.add(MoreFoodItems.HOPS);
            entries.add(MoreFoodItems.VANILLA_POD);
            entries.add(MoreFoodItems.YEAST);
            entries.add(MoreFoodItems.TOMATO_PUREE);
            entries.add(MoreFoodItems.GHERKIN);
            entries.add(MoreFoodItems.PEPPER);
            entries.add(MoreFoodItems.CHICKEN_SELECT);
            entries.add(MoreFoodItems.TOFFEE);
            entries.add(MoreFoodItems.SUSHI);
            entries.add(MoreFoodItems.ONIGIRI);
            entries.add(MoreFoodItems.SASHIMI);
            entries.add(MoreFoodItems.BEEF_SUB);
            entries.add(MoreFoodItems.CHEESE_WEDGE);
            entries.add(MoreFoodItems.TURKISH_DELIGHT);
            entries.add(MoreFoodItems.WAFFLE);
            entries.add(MoreFoodItems.PANCAKES);
            entries.add(MoreFoodItems.PICKLES);
            entries.add(MoreFoodItems.WARPED_BERRIES);
            entries.add(MoreFoodItems.PIZZA_SLICE);
            entries.add(MoreFoodItems.PIZZA);
            entries.add(MoreFoodItems.HOT_DOG);
            entries.add(MoreFoodItems.TACO);
            entries.add(MoreFoodItems.CHICKEN_FAJITA);
            entries.add(MoreFoodItems.BURRITO);
            entries.add(MoreFoodItems.KEBAB);
            entries.add(MoreFoodItems.BREAKFAST_SUB);
            entries.add(MoreFoodItems.BUTTER);
            entries.add(MoreFoodItems.SHROOMLIGHT_SLICES);
            entries.add(MoreFoodItems.ONION);
            entries.add(MoreFoodItems.COCONUT_MEAT);
            entries.add(MoreFoodItems.CHICKEN_SUB);
            entries.add(MoreFoodItems.ROTTEN_PORKCHOP);
            entries.add(MoreFoodItems.CEREAL);
            entries.add(MoreFoodItems.FUNGUS_STEW);
            entries.add(MoreFoodItems.SPAGHETTI);
            entries.add(MoreFoodItems.RAMEN_NOODLES);
            entries.add(MoreFoodItems.CUSTARD);
            entries.add(MoreFoodItems.NETHERWART_CHICKEN_SOUP);
            entries.add(MoreFoodItems.NETHERWART_MUSHROOM_SOUP);
            entries.add(MoreFoodItems.AMERICANO);
            entries.add(MoreFoodItems.CAPPUCCINO);
            entries.add(MoreFoodItems.MACCHIATO);
            entries.add(MoreFoodItems.MOCHA);
            entries.add(MoreFoodItems.TOFFEE_LATTE);
            entries.add(MoreFoodItems.VANILLA_LATTE);
            entries.add(MoreFoodItems.HOT_COFFEE);
            entries.add(MoreFoodItems.HOT_TEA);
            entries.add(MoreFoodItems.HOT_COCOA);
            entries.add(MoreFoodItems.VANILLA_EXTRACT);
            entries.add(MoreFoodItems.KETCHUP);
            entries.add(MoreFoodItems.COCONUT_MILK);
            entries.add(MoreFoodItems.SPARKLING_WATER_BOTTLE);
            entries.add(MoreFoodItems.CIDER);
            entries.add(MoreFoodItems.RED_WINE);
            entries.add(MoreFoodItems.WHITE_WINE);
            entries.add(MoreFoodItems.BEER);
            entries.add(MoreFoodItems.CREATIVE_HUNGER);
            entries.add(MoreFoodItems.MILK_CARTON);
            entries.add(MoreFoodItems.CREAM_CARTON);
            entries.add(MoreFoodItems.APPLESAUCE);
            entries.add(MoreFoodItems.BAKED_SWEET_POTATO);
            entries.add(MoreFoodItems.BEANS);
            entries.add(MoreFoodItems.BEEF_GOULASH);
            entries.add(MoreFoodItems.BEEF_RAVIOLI);
            entries.add(MoreFoodItems.BEEF_STEW);
            entries.add(MoreFoodItems.BUCKWHEAT);
            entries.add(MoreFoodItems.CHEESE_SPREAD);
            entries.add(MoreFoodItems.CHEESE_TORTELLINI);
            entries.add(MoreFoodItems.CHICKEN_SOUP);
            entries.add(MoreFoodItems.CHILI);
            entries.add(MoreFoodItems.CHOCOLATE_BANANA_MUFFIN);
            entries.add(MoreFoodItems.CHOCOLATE_PEANUT_BUTTER);
            entries.add(MoreFoodItems.CORNBREAD);
            entries.add(MoreFoodItems.CRANBERRIES);
            entries.add(MoreFoodItems.CUT_SWEET_POTATO);
            entries.add(MoreFoodItems.DRIED_CRANBERRIES);
            entries.add(MoreFoodItems.DRIED_RAISENS);
            entries.add(MoreFoodItems.GARLIC_MASHED_POTATOES);
            entries.add(MoreFoodItems.GUACAMOLE);
            entries.add(MoreFoodItems.HASH_BROWNS);
            entries.add(MoreFoodItems.JALAPENO_CHEESE_BUCKET);
            entries.add(MoreFoodItems.JALAPENO_CHEESE_SPREAD);
            entries.add(MoreFoodItems.JALAPENO_CHEESE_WEDGE);
            entries.add(MoreFoodItems.JALAPENO_ROUND_CHEESE);
            entries.add(MoreFoodItems.MAPLE_MUFFIN);
            entries.add(MoreFoodItems.MAPLE_SAP_BUCKET);
            entries.add(MoreFoodItems.MASHED_POTATOES);
            entries.add(MoreFoodItems.OATMEAL);
            entries.add(MoreFoodItems.ONION_RINGS);
            entries.add(MoreFoodItems.PEANUT_BUTTER);
            entries.add(MoreFoodItems.PEPPERMINT_RING);
            entries.add(MoreFoodItems.SWEET_POTATO);
            entries.add(MoreFoodItems.ALMONDS);
            entries.add(MoreFoodItems.AVOCADO);
            entries.add(MoreFoodItems.BLUEBERRIES);
            entries.add(MoreFoodItems.CABBAGE);
            entries.add(MoreFoodItems.CHERRIES);
            entries.add(MoreFoodItems.EGGPLANT);
            entries.add(MoreFoodItems.GARLIC);
            entries.add(MoreFoodItems.GARLIC_BULB);
            entries.add(MoreFoodItems.OATS);
            entries.add(MoreFoodItems.PEANUT);
            entries.add(MoreFoodItems.PEPPERMINT);
            entries.add(MoreFoodItems.PEPPERMINT_EXTRACT);
            entries.add(MoreFoodItems.PEPPERMINT_RING);
            entries.add(MoreFoodItems.POISONOUS_SWEET_POTATO);
            entries.add(MoreFoodItems.POISON_BERRIES);
            entries.add(MoreFoodItems.PRETZEL);
            entries.add(MoreFoodItems.PRETZEL_NUGGETS);
            entries.add(MoreFoodItems.PRETZEL_STICKS);
            entries.add(MoreFoodItems.ROASTED_PEANUT);
            entries.add(MoreFoodItems.ROASTED_SOYBEANS);
            entries.add(MoreFoodItems.SMOKED_ALMONDS);
            entries.add(MoreFoodItems.SOYBEANS);
            entries.add(MoreFoodItems.SPAGHETTI_WITH_MEATBALLS);
            entries.add(MoreFoodItems.SPINACH);
            entries.add(MoreFoodItems.SPINACH_FETTUCCINE);
            entries.add(MoreFoodItems.SWEET_MASHED_POTATOES);
            entries.add(MoreFoodItems.SWEET_POTATO_FRIES);
            entries.add(MoreFoodItems.TORTILLA_CHIPS);
            entries.add(MoreFoodItems.TORTILLA_WITH_CHEESE);
            entries.add(MoreFoodItems.TORTILLA_WITH_JALAPENO_CHEESE);
            entries.add(MoreFoodItems.TRAIL_MIX);

            // Holiday Features
            entries.add(MoreFoodItems.WHITE_CANDY);
            entries.add(MoreFoodItems.LIGHT_GRAY_CANDY);
            entries.add(MoreFoodItems.GRAY_CANDY);
            entries.add(MoreFoodItems.BLACK_CANDY);
            entries.add(MoreFoodItems.BROWN_CANDY);
            entries.add(MoreFoodItems.RED_CANDY);
            entries.add(MoreFoodItems.ORANGE_CANDY);
            entries.add(MoreFoodItems.YELLOW_CANDY);
            entries.add(MoreFoodItems.LIME_CANDY);
            entries.add(MoreFoodItems.GREEN_CANDY);
            entries.add(MoreFoodItems.CYAN_CANDY);
            entries.add(MoreFoodItems.LIGHT_BLUE_CANDY);
            entries.add(MoreFoodItems.BLUE_CANDY);
            entries.add(MoreFoodItems.PURPLE_CANDY);
            entries.add(MoreFoodItems.MAGENTA_CANDY);
            entries.add(MoreFoodItems.PINK_CANDY);
            entries.add(MoreFoodItems.CANDY_CORN);
            entries.add(MoreFoodItems.CANDY_CORN_BOWL);
            entries.add(MoreFoodItems.COOKED_PUMPKIN_SEEDS);
            entries.add(MoreFoodItems.COOKED_SALTED_PUMPKIN_SEEDS);
            entries.add(MoreFoodItems.GHAST_COOKIE);
        });

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.COMBAT).register(entries -> {
            entries.add(MoreFoodItems.WOODEN_KNIFE);
            entries.addAfter(MoreFoodItems.WOODEN_KNIFE, MoreFoodItems.STONE_KNIFE);
            entries.addAfter(MoreFoodItems.STONE_KNIFE, MoreFoodItems.IRON_KNIFE);
            entries.addAfter(MoreFoodItems.IRON_KNIFE, MoreFoodItems.GOLDEN_KNIFE);
            entries.addAfter(MoreFoodItems.GOLDEN_KNIFE, MoreFoodItems.COPPER_KNIFE);
            entries.addAfter(MoreFoodItems.COPPER_KNIFE, MoreFoodItems.DIAMOND_KNIFE);
            entries.addAfter(MoreFoodItems.DIAMOND_KNIFE, MoreFoodItems.NETHERITE_KNIFE);
        });

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.TOOLS).register(entries -> {
            entries.add(MoreFoodItems.WOODEN_SPOON);
        });

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.INGREDIENTS).register(entries -> {
            entries.add(MoreFoodItems.LARGE_PUMPKIN_PALE);
            entries.add(MoreFoodItems.SMALL_PUMPKIN_PALE);

            entries.add(MoreFoodItems.CHOCOLATE_PROTEIN_DRINK_MIX);
            entries.add(MoreFoodItems.CAPPUCCINO_DRINK_MIX);
            entries.add(MoreFoodItems.TROPICAL_PUNCH_BEVERAGE_POWDER);
            entries.add(MoreFoodItems.COCOA_BEVERAGE_POWDER);
            entries.add(MoreFoodItems.ORANGE_BEVERAGE_POWDER);
            entries.add(MoreFoodItems.ORANGE_BEVERAGE_POWDER);
            entries.add(MoreFoodItems.GRAPE_BEVERAGE_POWDER);
            entries.add(MoreFoodItems.LEMON_LIME_BEVERAGE_POWDER);

            entries.add(BottledItem.addUses(new ItemStack(MoreFoodItems.BOTTLED_BEER), 4));
            entries.add(BottledItem.addUses(new ItemStack(MoreFoodItems.BOTTLED_CIDER), 4));
            entries.add(BottledItem.addUses(new ItemStack(MoreFoodItems.BOTTLED_RED_WINE), 4));
            entries.add(BottledItem.addUses(new ItemStack(MoreFoodItems.BOTTLED_WHITE_WINE), 4));

            entries.add(MoreFoodItems.LARGE_BOWL);
            entries.add(MoreFoodItems.PANCAKE_MIX);
            entries.add(MoreFoodItems.GLASS_SHARD);
            entries.add(MoreFoodItems.PULP);
            entries.add(MoreFoodItems.WOODEN_TREE_TAP);
            entries.add(MoreFoodItems.CHEESE_BUCKET);
            entries.add(MoreFoodItems.OIL);
            entries.add(MoreFoodItems.BEER_GLASS);
            entries.add(MoreFoodItems.CORN_FLOUR);
            entries.add(MoreFoodItems.FLOUR);
            entries.add(MoreFoodItems.BEVERAGE_CUP);
            entries.add(MoreFoodItems.BOTTLE);
            entries.add(MoreFoodItems.CARTON);
            entries.add(MoreFoodItems.CHICKEN_SELECT_BOX);
            entries.add(MoreFoodItems.ICECRUSH_GLASS);
            entries.add(MoreFoodItems.TUMBLER_GLASS);
            entries.add(MoreFoodItems.FRY_WRAPPER);
            entries.add(MoreFoodItems.HOT_BEVERAGE_CUP);
            entries.add(MoreFoodItems.ICING);
            entries.add(MoreFoodItems.JAR);
            entries.add(MoreFoodItems.SODA_CAN);
            entries.add(MoreFoodItems.STARCH);
            entries.add(MoreFoodItems.WINE_GLASS);
            entries.add(MoreFoodItems.SUB_WRAPPER);
            entries.add(MoreFoodItems.SALT);
            entries.add(MoreFoodItems.NOODLES);
            entries.add(MoreFoodItems.PASTA);
            entries.add(MoreFoodItems.COCONUT);
            entries.add(MoreFoodItems.SPARKLING_WATER_BUCKET);
            entries.add(MoreFoodItems.GELATIN);

            entries.add(MealReadyToEatItem.addNbtLootTable(new ItemStack(MoreFoodItems.MEAL_READY_TO_EAT), "morefood:mre/default"));
        });

        ItemGroupEvents.modifyEntriesEvent(ItemGroups.BUILDING_BLOCKS).register(entries -> {
            entries.add(MoreFoodItems.CHERRY_SACK);
            entries.add(MoreFoodItems.ALMOND_SACK);
            entries.add(MoreFoodItems.AVOCADO_SACK);
            entries.add(MoreFoodItems.BANANA_SACK);
            entries.add(MoreFoodItems.BARLEY_SEED_SACK);
            entries.add(MoreFoodItems.BEAN_SACK);
            entries.add(MoreFoodItems.BLUEBERRY_SACK);
            entries.add(MoreFoodItems.BLUEBERRY_SEED_SACK);
            entries.add(MoreFoodItems.BUCKWHEAT_SACK);
            entries.add(MoreFoodItems.CABBAGE_SACK);
            entries.add(MoreFoodItems.CABBAGE_SEED_SACK);
            entries.add(MoreFoodItems.CHOCOLATE_CHUNK_OATMEAL_COOKIE_SACK);
            entries.add(MoreFoodItems.COCONUT_SACK);
            entries.add(MoreFoodItems.COFFEE_BEAN_SACK);
            entries.add(MoreFoodItems.CORN_FLOUR_SACK);
            entries.add(MoreFoodItems.CORN_COB_SACK);
            entries.add(MoreFoodItems.CORN_SACK);
            entries.add(MoreFoodItems.CRANBERRY_SACK);
            entries.add(MoreFoodItems.EGGPLANT_SACK);
            entries.add(MoreFoodItems.EGGPLANT_SEED_SACK);
            entries.add(MoreFoodItems.FLOUR_SACK);
            entries.add(MoreFoodItems.GARLIC_SACK);
            entries.add(MoreFoodItems.GHERKIN_SACK);
            entries.add(MoreFoodItems.GHERKIN_SEED_SACK);
            entries.add(MoreFoodItems.GRAPE_SACK);
            entries.add(MoreFoodItems.GRAPE_SEED_SACK);
            entries.add(MoreFoodItems.HOPS_SACK);
            entries.add(MoreFoodItems.HOPS_SEED_SACK);
            entries.add(MoreFoodItems.LEMON_SACK);
            entries.add(MoreFoodItems.LETTUCE_SACK);
            entries.add(MoreFoodItems.LETTUCE_SEED_SACK);
            entries.add(MoreFoodItems.NETHER_COOKIE_SACK);
            entries.add(MoreFoodItems.OATMEAL_COOKIE_SACK);
            entries.add(MoreFoodItems.OAT_SACK);
            entries.add(MoreFoodItems.OAT_SEED_SACK);
            entries.add(MoreFoodItems.OLIVES_SACK);
            entries.add(MoreFoodItems.ONION_SACK);
            entries.add(MoreFoodItems.ONION_SEED_SACK);
            entries.add(MoreFoodItems.ORANGE_SACK);
            entries.add(MoreFoodItems.PEANUT_SACK);
            entries.add(MoreFoodItems.PEANUT_SEED_SACK);
            entries.add(MoreFoodItems.PEPPER_SACK);
            entries.add(MoreFoodItems.PEPPER_SEED_SACK);
            entries.add(MoreFoodItems.PLUM_SACK);
            entries.add(MoreFoodItems.POISONOUS_SWEET_POTATO_SACK);
            entries.add(MoreFoodItems.POISON_BERRY_SACK);
            entries.add(MoreFoodItems.RASPBERRY_SACK);
            entries.add(MoreFoodItems.RASPBERRY_SEED_SACK);
            entries.add(MoreFoodItems.RICE_SACK);
            entries.add(MoreFoodItems.RICE_SEED_SACK);
            entries.add(MoreFoodItems.SOYBEAN_SACK);
            entries.add(MoreFoodItems.SPINACH_SACK);
            entries.add(MoreFoodItems.SPINACH_SEED_SACK);
            entries.add(MoreFoodItems.STRAWBERRY_SACK);
            entries.add(MoreFoodItems.STRAWBERRY_SEED_SACK);
            entries.add(MoreFoodItems.SUGAR_COOKIE_SACK);
            entries.add(MoreFoodItems.SWEET_POTATO_SACK);
            entries.add(MoreFoodItems.TEA_LEAF_SACK);
            entries.add(MoreFoodItems.TEA_SEED_SACK);
            entries.add(MoreFoodItems.TOMATO_SACK);
            entries.add(MoreFoodItems.TOMATO_SEED_SACK);
            entries.add(MoreFoodItems.VANILLA_POD_SACK);
            entries.add(MoreFoodItems.VANILLA_SEED_SACK);
            entries.add(MoreFoodItems.YEAST_SACK);
        });
    }

}
