give @s morefood:pepper_seed_sack
give @s morefood:plum_sack
give @s morefood:poisonous_sweet_potato_sack
give @s morefood:poison_berry_sack
give @s morefood:raspberry_sack
give @s morefood:raspberry_seed_sack
give @s morefood:rice_sack
give @s morefood:rice_seed_sack
give @s morefood:soybean_sack
give @s morefood:spinach_sack
give @s morefood:spinach_seed_sack
give @s morefood:strawberry_sack
give @s morefood:strawberry_seed_sack
give @s morefood:sugar_cookie_sack
give @s morefood:sweet_potato_sack
give @s morefood:tea_leaf_sack
give @s morefood:tea_seed_sack
give @s morefood:tomato_sack
give @s morefood:tomato_seed_sack
give @s morefood:vanilla_pod_sack
give @s morefood:vanilla_seed_sack
give @s morefood:yeast_sack
give @s morefood:soybean_bush
give @s morefood:spearmint_plant
give @s morefood:spinach_crop
give @s morefood:sweet_potatoes
give @s morefood:watermint_plant
give @s morefood:wooden_tree_tap
give @s morefood:apple_hanging_fruit
give @s morefood:apple_sapling_block
give @s morefood:banana_hanging_fruit
give @s morefood:banana_sapling_block
give @s morefood:barley_crop
give @s morefood:black_candle_chocolate_cake
give @s morefood:black_candle_pound_cake
give @s morefood:black_candle_rainbow_cake
