give @s morefood:almond_sapling_block
give @s morefood:avocado_sapling_block
give @s morefood:bean_bush
give @s morefood:blueberry_bush
give @s morefood:buckwheat_crop
give @s morefood:cabbage_crop
give @s morefood:cranberry_bush
give @s morefood:eggplant_bush
give @s morefood:fertile_soil
give @s morefood:garlic_crop
give @s morefood:hanging_almond
give @s morefood:hanging_avocado
give @s morefood:oat_crop
give @s morefood:peanut_crop
give @s morefood:peppermint_bush
give @s morefood:poison_berry_bush
give @s morefood:almond_sack
give @s morefood:avocado_sack
give @s morefood:banana_sack
give @s morefood:barley_seed_sack
give @s morefood:bean_sack
