give @s morefood:blueberry_sack
give @s morefood:blueberry_seed_sack
give @s morefood:buckwheat_sack
give @s morefood:cabbage_sack
give @s morefood:cabbage_seed_sack
give @s morefood:chocolate_chunk_oatmeal_cookie_sack
give @s morefood:coconut_sack
give @s morefood:coffee_bean_sack
give @s morefood:corn_flour_sack
give @s morefood:corn_cob_sack
give @s morefood:corn_sack
give @s morefood:cranberry_sack
give @s morefood:eggplant_sack
give @s morefood:eggplant_seed_sack
give @s morefood:flour_sack
give @s morefood:garlic_sack
give @s morefood:gherkin_sack
give @s morefood:gherkin_seed_sack
give @s morefood:grape_sack
give @s morefood:grape_seed_sack
give @s morefood:hops_sack
give @s morefood:hops_seed_sack
give @s morefood:lemon_sack
give @s morefood:lettuce_sack
give @s morefood:lettuce_seed_sack
give @s morefood:nether_cookie_sack
give @s morefood:oatmeal_cookie_sack
give @s morefood:oat_sack
give @s morefood:oat_seed_sack
give @s morefood:olive_sack
give @s morefood:onion_sack
give @s morefood:onion_seed_sack
give @s morefood:orange_sack
give @s morefood:peanut_sack
give @s morefood:peanut_seed_sack
give @s morefood:pepper_sack
