give @s morefood:black_candle_redwhiteblue_cake
give @s morefood:blue_candle_chocolate_cake
give @s morefood:blue_candle_pound_cake
give @s morefood:blue_candle_rainbow_cake
give @s morefood:blue_candle_redwhiteblue_cake
give @s morefood:brown_candle_chocolate_cake
give @s morefood:brown_candle_pound_cake
give @s morefood:brown_candle_rainbow_cake
give @s morefood:brown_candle_redwhiteblue_cake
give @s morefood:candle_chocolate_cake
give @s morefood:candle_pound_cake
give @s morefood:candle_rainbow_cake
give @s morefood:candle_redwhiteblue_cake
give @s morefood:cyan_candle_chocolate_cake
give @s morefood:cyan_candle_pound_cake
give @s morefood:cyan_candle_rainbow_cake
give @s morefood:cyan_candle_redwhiteblue_cake
give @s morefood:gray_candle_chocolate_cake
give @s morefood:gray_candle_pound_cake
give @s morefood:gray_candle_rainbow_cake
give @s morefood:gray_candle_redwhiteblue_cake
give @s morefood:green_candle_chocolate_cake
give @s morefood:green_candle_pound_cake
give @s morefood:green_candle_rainbow_cake
give @s morefood:green_candle_redwhiteblue_cake
give @s morefood:light_blue_candle_chocolate_cake
give @s morefood:light_blue_candle_pound_cake
give @s morefood:light_blue_candle_rainbow_cake
give @s morefood:light_blue_candle_redwhiteblue_cake
give @s morefood:light_gray_candle_chocolate_cake
give @s morefood:light_gray_candle_pound_cake
give @s morefood:light_gray_candle_rainbow_cake
give @s morefood:light_gray_candle_redwhiteblue_cake
give @s morefood:lime_candle_chocolate_cake
give @s morefood:lime_candle_pound_cake
give @s morefood:lime_candle_rainbow_cake
