give @s morefood:bacon_egg_muffin
give @s morefood:bacon_egg_sandwich
give @s morefood:baked_sweet_potato
give @s morefood:banana
give @s morefood:banana_sapling
give @s morefood:barley_seeds
give @s morefood:bat_meat
give @s morefood:beef_sub
give @s morefood:beer_glass
give @s morefood:beverage_cup
give @s morefood:blue_cupcake
give @s morefood:bottle
give @s morefood:bread_loaf
give @s morefood:breakfast_sub
give @s morefood:burger_bun
give @s morefood:burrito
give @s morefood:butter
give @s morefood:carton
give @s morefood:cereal
give @s morefood:cheese_bucket
give @s morefood:cheese_toastie
give @s morefood:cheese_wedge
give @s morefood:chicken_fajita
give @s morefood:chicken_nugget
give @s morefood:chicken_select
give @s morefood:chicken_select_box
give @s morefood:chicken_sub
give @s morefood:chocolate_cake
give @s morefood:coconut
give @s morefood:coconut_meat
give @s morefood:coffee_beans
give @s morefood:cooked_bacon
give @s morefood:cooked_bat_meat
give @s morefood:cooked_chicken_nugget
give @s morefood:cooked_chicken_piece
give @s morefood:hamburger_patty
