give @s morefood:popcorn
give @s morefood:popcorn_bucket
give @s morefood:rainbow_cake
give @s morefood:ramen_noodles
give @s morefood:raspberry
give @s morefood:raspberry_seeds
give @s morefood:redwhiteblue_cake
give @s morefood:rice
give @s morefood:rice_pudding
give @s morefood:rice_seeds
give @s morefood:rotten_porkchop
give @s morefood:truckle_of_cheese
give @s morefood:salt
give @s morefood:sashimi
give @s morefood:breakfast_sausage
give @s morefood:sausage_egg_muffin
give @s morefood:sausage_egg_sandwich
give @s morefood:shroomlight_slice
give @s morefood:soda_can
give @s morefood:spaghetti
give @s morefood:sparkling_water_bucket
give @s morefood:squid
give @s morefood:starch
give @s morefood:knife_stone
give @s morefood:strawberry
give @s morefood:strawberry_jelly
give @s morefood:strawberry_seeds
give @s morefood:submarine_sandwich_bun
give @s morefood:sushi
give @s morefood:taco
give @s morefood:tea_leaves
give @s morefood:tea_seeds
give @s morefood:toast
give @s morefood:toffee
give @s morefood:tomato
