give @s morefood:bottled_red_wine
give @s morefood:bottled_red_wine_25
give @s morefood:bottled_red_wine_50
give @s morefood:bottled_red_wine_75
give @s morefood:bottled_white_wine_0
give @s morefood:bottled_white_wine
give @s morefood:bottled_white_wine_25
give @s morefood:bottled_white_wine_50
give @s morefood:bottled_white_wine_75
give @s morefood:cappuccino
give @s morefood:cider
give @s morefood:coconut_milk
give @s morefood:cream_carton
give @s morefood:hot_cocoa
give @s morefood:hot_coffee
give @s morefood:hot_tea
give @s morefood:apple_ice_crush
give @s morefood:apple_raspberry_ice_crush
give @s morefood:berry_ice_crush
give @s morefood:grape_ice_crush
give @s morefood:lemon_ice_crush
give @s morefood:melon_ice_crush
give @s morefood:mixed_fruit_ice_crush
give @s morefood:strawberry_ice_crush
give @s morefood:orange_ice_crush
give @s morefood:apple_juice
give @s morefood:berry_juice
give @s morefood:grape_juice
give @s morefood:lemon_juice
give @s morefood:melon_juice
give @s morefood:mixed_fruit_juice
give @s morefood:orange_juice
give @s morefood:strawberry_juice
give @s morefood:tomato_juice
give @s morefood:macchiato
give @s morefood:banana_milkshake
