give @s morefood:bottled_red_wine
give @s morefood:bottled_red_wine_25
give @s morefood:bottled_red_wine_50
give @s morefood:bottled_red_wine_75
give @s morefood:bottled_white_wine_0
give @s morefood:bottled_white_wine
give @s morefood:bottled_white_wine_25
give @s morefood:bottled_white_wine_50
give @s morefood:bottled_white_wine_75
give @s morefood:cappuccino
give @s morefood:cider
give @s morefood:coconut_milk
give @s morefood:cream_carton
give @s morefood:hot_cocoa
give @s morefood:hot_coffee
give @s morefood:hot_tea
give @s morefood:icecrush_apple
give @s morefood:icecrush_apple_raspberry
give @s morefood:icecrush_berry
give @s morefood:icecrush_grape
give @s morefood:icecrush_lemon
give @s morefood:icecrush_melon
give @s morefood:icecrush_mixed_fruit
give @s morefood:icecrush_strawberry
give @s morefood:icecrush_orange
give @s morefood:juice_apple
give @s morefood:juice_berry
give @s morefood:juice_grape
give @s morefood:juice_lemon
give @s morefood:juice_melon
give @s morefood:juice_mixed_fruit
give @s morefood:juice_orange
give @s morefood:juice_strawberry
give @s morefood:juice_tomato
give @s morefood:macchiato
give @s morefood:milkshake_banana
