give @s morefood:cooked_hoglin_meat
give @s morefood:cooked_frankfurter_sausage
give @s morefood:cooked_breakfast_sausage
give @s morefood:veggie_burger_patty
give @s morefood:cooked_potato_wedges
give @s morefood:copper_knife
give @s morefood:corn
give @s morefood:corn_flour
give @s morefood:corncob
give @s morefood:creative_hunger
give @s morefood:custard
give @s morefood:bread_slice
give @s morefood:french_fries
give @s morefood:dark_chocolate
give @s morefood:knife_diamond
give @s morefood:chocolate_doughnut
give @s morefood:coffee_doughnut
give @s morefood:iced_doughnut
give @s morefood:pink_ice_doughnut
give @s morefood:plain_doughnut
give @s morefood:strawberry_doughnut
give @s morefood:toffee_doughnut
give @s morefood:dough
give @s morefood:americano
give @s morefood:beer
give @s morefood:bottled_beer_0
give @s morefood:bottled_beer
give @s morefood:bottled_beer_25
give @s morefood:bottled_beer_50
give @s morefood:bottled_beer_75
give @s morefood:bottled_cider_0
give @s morefood:bottled_cider
give @s morefood:bottled_cider_25
give @s morefood:bottled_cider_50
give @s morefood:bottled_cider_75
give @s morefood:bottled_red_wine_0
