give @s morefood:almonds
give @s morefood:almond_sapling
give @s morefood:apple_sauce
give @s morefood:avocado
give @s morefood:avocado_sapling
give @s morefood:beans
give @s morefood:bean_seeds
give @s morefood:beef_goulash
give @s morefood:beef_ravioli
give @s morefood:beef_stew
give @s morefood:blueberries
give @s morefood:blueberry_seeds
give @s morefood:blueberry_syrup
give @s morefood:breadsticks
give @s morefood:breadsticks_with_glowberry_jam
give @s morefood:breadsticks_with_jam
give @s morefood:breadsticks_with_peanut_butter
give @s morefood:buckwheat
give @s morefood:burnt_marshmallow_on_a_stick
give @s morefood:cabbage
give @s morefood:cabbage_seeds
give @s morefood:cappuccino_drink_mix
give @s morefood:cheese_spread
give @s morefood:cheese_tortellini
give @s morefood:chicken_soup
give @s morefood:chili
give @s morefood:chocolate_banana_muffin
give @s morefood:chocolate_chunk_oatmeal_cookie
give @s morefood:chocolate_peanut_butter
give @s morefood:chocolate_protein_drink_mix
give @s morefood:chocolate_pudding
give @s morefood:cocoa_beverage_powder
give @s morefood:cooked_marshmallow_on_a_stick
give @s morefood:cornbread
give @s morefood:crackers
give @s morefood:crackers_with_cheese
