give @s morefood:poison_berries
give @s morefood:pork_sausage_burger
give @s morefood:pound_cake
give @s morefood:pretzel
give @s morefood:pretzel_nuggets
give @s morefood:pretzel_sticks
give @s morefood:pulled_beef_burger
give @s morefood:pulp
give @s morefood:raspberry_syrup
give @s morefood:roasted_peanut
give @s morefood:roasted_soybeans
give @s morefood:roasted_sunflower_seeds
give @s morefood:smoked_almonds
give @s morefood:soybeans
give @s morefood:spaghetti_with_meatballs
give @s morefood:spearmint
give @s morefood:spinach
give @s morefood:spinach_fettuccine
give @s morefood:spinach_seeds
give @s morefood:strawberry_syrup
give @s morefood:sugar_cookie
give @s morefood:sweet_mashed_potatoes
give @s morefood:sweet_potato
give @s morefood:sweet_french_fry_pot
give @s morefood:tortilla_chips
give @s morefood:tortilla_with_cheese
give @s morefood:tortilla_with_jalapeno_cheese
give @s morefood:trail_mix
give @s morefood:tropical_punch_beverage_powder
give @s morefood:tuna_sandwich
give @s morefood:vanilla_pudding
give @s morefood:watermint
give @s morefood:white_chocolate_covered_apple
give @s morefood:wooden_tree_tap.item
give @s morefood:apple_sapling
give @s morefood:bacon
