give @s morefood:knife_golden
give @s morefood:grape
give @s morefood:grape_seeds
give @s morefood:hamburger
give @s morefood:raw_hamburger_patty
give @s morefood:hoglin_meat
give @s morefood:hops
give @s morefood:hops_seeds
give @s morefood:hotdog
give @s morefood:hotdog_bun
give @s morefood:hotdog_sausage
give @s morefood:hot_beverage_cup
give @s morefood:icecream_banana
give @s morefood:icecream_chocolate
give @s morefood:icecream_cone
give @s morefood:icecream_strawberry
give @s morefood:icecream_toffee
give @s morefood:icecream_vanilla
give @s morefood:ice_bowl
give @s morefood:icing
give @s morefood:knife_iron
give @s morefood:jam
give @s morefood:jar
give @s morefood:jelly_sandwich
give @s morefood:kebab
give @s morefood:ketchup
give @s morefood:lemon
give @s morefood:lemon_sapling
give @s morefood:lettuce
give @s morefood:lettuce_seeds
give @s morefood:milk_chocolate
give @s morefood:muffin_bun
give @s morefood:netherite_apple
give @s morefood:knife_netherite
give @s morefood:netherwart_chicken_soup
give @s morefood:netherwart_mushroom_soup
