give @s morefood:nether_cookie
give @s morefood:noodles
give @s morefood:olives
give @s morefood:olive_sapling
give @s morefood:onigiri
give @s morefood:onion
give @s morefood:onion_seeds
give @s morefood:orange
give @s morefood:orange_jelly
give @s morefood:orange_sapling
give @s morefood:palm_sapling
give @s morefood:pancakes
give @s morefood:pasta
give @s morefood:pepper
give @s morefood:pepper_seeds
give @s morefood:pickles
give @s morefood:pie_apple
give @s morefood:pie_apple_raspberry
give @s morefood:pie_base
give @s morefood:pie_berry
give @s morefood:pie_cheese
give @s morefood:pie_chicken
give @s morefood:pie_chocolate
give @s morefood:pie_lemon
give @s morefood:pie_plum
give @s morefood:pie_pork
give @s morefood:pie_steak
give @s morefood:pie_strawberry
give @s morefood:pie_toffee
give @s morefood:pink_cupcake
give @s morefood:pitta_bread
give @s morefood:pizza
give @s morefood:pizza_base
give @s morefood:pizza_slice
give @s morefood:plum
give @s morefood:plum_sapling
