give @s morefood:chocolate_milkshake
give @s morefood:strawberry_milkshake
give @s morefood:milk_carton
give @s morefood:mocha
give @s morefood:oil
give @s morefood:red_wine
give @s morefood:banana_smoothie
give @s morefood:berry_smoothie
give @s morefood:grape_smoothie
give @s morefood:mixed_fruit_smoothie
give @s morefood:raspberry_smoothie
give @s morefood:strawberry_smoothie
give @s morefood:apple_soda
give @s morefood:berry_soda
give @s morefood:grape_soda
give @s morefood:lemon_soda
give @s morefood:orange_soda
give @s morefood:strawberry_soda
give @s morefood:sparkling_water_bottle
give @s morefood:toffee_latte
give @s morefood:vanilla_extract
give @s morefood:vanilla_latte
give @s morefood:white_wine
give @s morefood:ice_crush_glass
give @s morefood:tumbler_glass
give @s morefood:flour
give @s morefood:fried_egg
give @s morefood:fried_squid
give @s morefood:french_fry_pot
give @s morefood:fry_wrapper
give @s morefood:fungus_stew
give @s morefood:gelatin
give @s morefood:gherkin
give @s morefood:gherkin_seeds
