give @s morefood:nether_cookie
give @s morefood:noodles
give @s morefood:olives
give @s morefood:olive_sapling
give @s morefood:onigiri
give @s morefood:onion
give @s morefood:onion_seeds
give @s morefood:orange
give @s morefood:orange_jelly
give @s morefood:orange_sapling
give @s morefood:palm_sapling
give @s morefood:pancakes
give @s morefood:pasta
give @s morefood:pepper
give @s morefood:pepper_seeds
give @s morefood:pickles
give @s morefood:apple_pie
give @s morefood:apple_raspberry_pie
give @s morefood:pie_crust
give @s morefood:berry_pie
give @s morefood:cheese_pie
give @s morefood:chicken_pie
give @s morefood:chocolate_pie
give @s morefood:lemon_pie
give @s morefood:plum_pie
give @s morefood:pork_pie
give @s morefood:beef_pie
give @s morefood:strawberry_pie
give @s morefood:toffee_pie
give @s morefood:pink_cupcake
give @s morefood:pitta_bread
give @s morefood:pizza
give @s morefood:pizza_crust
give @s morefood:pizza_slice
give @s morefood:plum
give @s morefood:plum_sapling
