package com.legopitstop.morefood.init;

import com.legopitstop.morefood.MoreFood;
import com.legopitstop.morefood.blocks.BlockItemBase;
import com.legopitstop.morefood.items.*;
import com.legopitstop.morefood.items.BottleItem;
import net.minecraft.world.item.*;
import net.minecraftforge.fmllegacy.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class MoreFoodItems {
    public static DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, MoreFood.MOD_ID);
    // BLOCK ITEMS
    public static final RegistryObject<Item> COFFEE_BEANS = ITEMS.register("coffee_beans", () -> new BlockItemBase(MoreFoodBlocks.COFFEE_BUSH.get()));
    public static final RegistryObject<Item> GHERKIN_SEEDS = ITEMS.register("gherkin_seeds", () -> new BlockItemBase(MoreFoodBlocks.GHERKIN_BUSH.get()));
    public static final RegistryObject<Item> GRAPE_SEEDS = ITEMS.register("grape_seeds", () -> new BlockItemBase(MoreFoodBlocks.GRAPE_BUSH.get()));
    public static final RegistryObject<Item> RASPBERRY_SEEDS = ITEMS.register("raspberry_seeds", () -> new BlockItemBase(MoreFoodBlocks.RASPBERRY_BUSH.get()));
    public static final RegistryObject<Item> STRAWBERRY_SEEDS = ITEMS.register("strawberry_seeds", () -> new BlockItemBase(MoreFoodBlocks.STRAWBERRY_BUSH.get()));
    public static final RegistryObject<Item> TEA_SEEDS = ITEMS.register("tea_seeds", () -> new BlockItemBase(MoreFoodBlocks.TEA_BUSH.get()));
    public static final RegistryObject<Item> TOMATO_SEEDS = ITEMS.register("tomato_seeds", () -> new BlockItemBase(MoreFoodBlocks.TOMATO_BUSH.get()));
    public static final RegistryObject<Item> VANILLA_SEEDS = ITEMS.register("vanilla_seeds", () -> new BlockItemBase(MoreFoodBlocks.VANILLA_BUSH.get()));
    public static final RegistryObject<Item> PEPPER_SEEDS = ITEMS.register("pepper_seeds", () -> new BlockItemBase(MoreFoodBlocks.PEPPER_BUSH.get()));

    public static final RegistryObject<Item> BARLEY_SEEDS = ITEMS.register("barley_seeds", () -> new BlockItemBase(MoreFoodBlocks.BARLEY.get()));
    public static final RegistryObject<Item> CORN_SEEDS = ITEMS.register("corn_seeds", () -> new BlockItemBase(MoreFoodBlocks.CORN.get()));
    public static final RegistryObject<Item> HOPS_SEEDS = ITEMS.register("hops_seeds", () -> new BlockItemBase(MoreFoodBlocks.HOPS.get()));
    public static final RegistryObject<Item> LETTUCE_SEEDS = ITEMS.register("lettuce_seeds", () -> new BlockItemBase(MoreFoodBlocks.LETTUCE.get()));
    public static final RegistryObject<Item> RICE_SEEDS = ITEMS.register("rice_seeds", () -> new BlockItemBase(MoreFoodBlocks.RICE.get()));
    public static final RegistryObject<Item> ONION_SEEDS = ITEMS.register("onion_seeds", () -> new BlockItemBase(MoreFoodBlocks.ONION.get()));

    public static final RegistryObject<Item> CHOCOLATE_CAKE_ITEM = ITEMS.register("chocolate_cake", () -> new BlockItemBase(MoreFoodBlocks.CHOCOLATE_CAKE.get()));
    public static final RegistryObject<Item> RAINBOW_CAKE_ITEM = ITEMS.register("rainbow_cake", () -> new BlockItemBase(MoreFoodBlocks.RAINBOW_CAKE.get()));
    public static final RegistryObject<Item> REDWHITEBLUE_CAKE_ITEM = ITEMS.register("redwhiteblue_cake", () -> new BlockItemBase(MoreFoodBlocks.REDWHITEBLUE_CAKE.get()));

    // FOODS
    public static final RegistryObject<Item> RICE = ITEMS.register("rice", () -> new FoodItemBase(4,2.0F, 64));
    public static final RegistryObject<Item> HAMBURGER = ITEMS.register("hamburger", () -> new FoodItemBase(4,1.2F, 64));
    public static final RegistryObject<Item> NETHERITE_APPLE = ITEMS.register("netherite_apple", () -> new FoodItemBase(4,1.2F, 64));
    public static final RegistryObject<Item> VEGANBURGER = ITEMS.register("veganburger", () -> new FoodItemBase(4,1.2F, 64));
    public static final RegistryObject<Item> JELLY_SANDWICH = ITEMS.register("jelly_sandwich", () -> new FoodItemBase(4,1.2F, 64));
    public static final RegistryObject<Item> ROUND_CHEESE = ITEMS.register("round_cheese", () -> new FoodItemBase(4,1.2F, 64));
    public static final RegistryObject<Item> ORANGE = ITEMS.register("orange", () -> new FoodItemBase(4,0.3F, 64) );
    public static final RegistryObject<Item> GRAPE = ITEMS.register("grape", () -> new FoodItemBase(4,0.3F, 64) );
    public static final RegistryObject<Item> TOMATO = ITEMS.register("tomato", () -> new FoodItemBase(4,0.3F, 64) );
    public static final RegistryObject<Item> BANANA = ITEMS.register("banana", () -> new FoodItemBase(4,0.3F, 64) );
    public static final RegistryObject<Item> LEMON = ITEMS.register("lemon", () -> new FoodItemBase(4,0.3F, 64) );
    public static final RegistryObject<Item> STRAWBERRY = ITEMS.register("strawberry", () -> new FoodItemBase(4,0.3F, 64) );
    public static final RegistryObject<Item> TEA_LEAVES = ITEMS.register("tea_leaves", () -> new FoodItemBase(4,0.3F, 64) );
    public static final RegistryObject<Item> PLUM = ITEMS.register("plum", () -> new FoodItemBase(4,0.3F, 64) );
    public static final RegistryObject<Item> OLIVES = ITEMS.register("olives", () -> new FoodItemBase(4,0.3F, 64) );
    public static final RegistryObject<Item> RASPBERRY = ITEMS.register("raspberry", () -> new FoodItemBase(4,0.3F, 64) );
    public static final RegistryObject<Item> CUT_FRIES = ITEMS.register("cut_fries", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> COOKED_WEDGES = ITEMS.register("cooked_wedges", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> FRIES = ITEMS.register("fries", () -> new FoodItemBase(1,0.6F, 64) );
    public static final RegistryObject<Item> CORN_ON_COB = ITEMS.register("corn_on_cob", () -> new FoodItemBase(1,0.6F, 64) );
    public static final RegistryObject<Item> DOUGH = ITEMS.register("dough", () -> new FoodItemBase(1,0.6F, 64) );
    public static final RegistryObject<Item> JAM = ITEMS.register("jam", () -> new FoodItemBase(1,0.6F, 64) );
    public static final RegistryObject<Item> LETTUCE = ITEMS.register("lettuce", () -> new FoodItemBase(1,0.6F, 64) );
    public static final RegistryObject<Item> HOPS = ITEMS.register("hops", () -> new FoodItemBase(1,0.6F, 64) );
    public static final RegistryObject<Item> VANILLA_POD = ITEMS.register("vanilla_pod", () -> new FoodItemBase(1,0.6F, 64) );
    public static final RegistryObject<Item> YEAST = ITEMS.register("yeast", () -> new FoodItemBase(1,0.6F, 64) );
    public static final RegistryObject<Item> TOMATO_PUREE = ITEMS.register("tomato_puree", () -> new FoodItemBase(1,0.6F, 64) );
    public static final RegistryObject<Item> GHERKIN = ITEMS.register("gherkin", () -> new FoodItemBase(1,0.6F, 64) );
    public static final RegistryObject<Item> PEPPER = ITEMS.register("pepper", () -> new FoodItemBase(1,0.6F, 64) );
    public static final RegistryObject<Item> TOAST = ITEMS.register("toast", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> SUB_BUN = ITEMS.register("sub_bun", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> CUT_BREAD = ITEMS.register("cut_bread", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> HOTDOG_BUN = ITEMS.register("hotdog_bun", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> TORTILLA = ITEMS.register("tortilla", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> MUFFIN_BUN = ITEMS.register("muffin_bun", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> BURGER_BUN = ITEMS.register("burger_bun", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> PITTA_BREAD = ITEMS.register("pitta_bread", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> PIZZA_BASE = ITEMS.register("pizza_base", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> BREAD_LOAF = ITEMS.register("bread_loaf", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> CHICKEN_SELECT = ITEMS.register("chicken_select", () -> new FoodItemBase(6,0.6F, 64) );
    public static final RegistryObject<Item> TOFFEE = ITEMS.register("toffee", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> SUSHI = ITEMS.register("sushi", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> ONIGIRI = ITEMS.register("onigiri", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> SASHIMI = ITEMS.register("sashimi", () -> new FoodItemBase(5,0.6F, 64) );
    public static final RegistryObject<Item> BEEF_SUB = ITEMS.register("beef_sub", () -> new FoodItemBase(8,0.8F, 64) );
    public static final RegistryObject<Item> CHEESE_WEDGE = ITEMS.register("cheese_wedge", () -> new FoodItemBase(6,0.8F, 64) );
    public static final RegistryObject<Item> MILK_CHOCOLATE = ITEMS.register("milk_chocolate", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> WHITE_CHOCOLATE = ITEMS.register("white_chocolate", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> DARK_CHOCOLATE = ITEMS.register("dark_chocolate", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> ICECREAM_CONE = ITEMS.register("icecream_cone", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> TURKISH_DELIGHT = ITEMS.register("turkish_delight", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> BANANA_ICECREAM = ITEMS.register("banana_icecream", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> CHOCOLATE_ICECREAM = ITEMS.register("chocolate_icecream", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> STRAWBERRY_ICECREAM = ITEMS.register("strawberry_icecream", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> CHOCOLATE_DONUT = ITEMS.register("chocolate_donut", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> COFFEE_DONUT = ITEMS.register("coffee_donut", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> ICED_DONUT = ITEMS.register("iced_donut", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> PINK_ICE_DONUT = ITEMS.register("pink_ice_donut", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> PLAIN_DONUT = ITEMS.register("plain_donut", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> STRAWBERRY_DONUT = ITEMS.register("strawberry_donut", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> PINK_CUPCAKE = ITEMS.register("pink_cupcake", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> BLUE_CUPCAKE = ITEMS.register("blue_cupcake", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> TOFFEE_ICECREAM = ITEMS.register("toffee_icecream", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> VANILLA_ICECREAM = ITEMS.register("vanilla_icecream", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> WAFFLE = ITEMS.register("waffle", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> TOFFEE_DONUT = ITEMS.register("toffee_donut", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> PANCAKES = ITEMS.register("pancakes", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> NETHER_COOKIE = ITEMS.register("nether_cookie", () -> new FoodItemBase(2,0.1F, 64) );
    public static final RegistryObject<Item> PICKLES = ITEMS.register("pickles", () -> new FoodItemBase(1,0.3F, 64) );
    public static final RegistryObject<Item> POPCORN = ITEMS.register("popcorn", () -> new FoodItemBase(1,0.3F, 64) );
    public static final RegistryObject<Item> WARPED_BERRIES = ITEMS.register("warped_berries", () -> new FoodItemBase(1,0.3F, 64) );
    public static final RegistryObject<Item> PIZZA_SLICE = ITEMS.register("pizza_slice", () -> new FoodItemBase(6,1.2F, 64) );
    public static final RegistryObject<Item> PIZZA = ITEMS.register("pizza", () -> new FoodItemBase(6,1.2F, 64) );
    public static final RegistryObject<Item> HOTDOG = ITEMS.register("hotdog", () -> new FoodItemBase(6,1.2F, 64) );
    public static final RegistryObject<Item> POPCORN_BUCKET = ITEMS.register("popcorn_bucket", () -> new FoodItemBase(6,1.2F, 1) );
    public static final RegistryObject<Item> TACO = ITEMS.register("taco", () -> new FoodItemBase(6,1.2F, 64) );
    public static final RegistryObject<Item> CHICKEN_FAJITA = ITEMS.register("chicken_fajita", () -> new FoodItemBase(6,1.2F, 64) );
    public static final RegistryObject<Item> BURRITO = ITEMS.register("burrito", () -> new FoodItemBase(6,1.2F, 64) );
    public static final RegistryObject<Item> KEBAB = ITEMS.register("kebab", () -> new FoodItemBase(6,1.2F, 64) );
    public static final RegistryObject<Item> BACON_EGG_SANDWICH = ITEMS.register("bacon_egg_sandwich", () -> new FoodItemBase(6,1.2F, 64) );
    public static final RegistryObject<Item> BACON_EGG_MUFFIN = ITEMS.register("bacon_egg_muffin", () -> new FoodItemBase(6,1.2F,64));
    public static final RegistryObject<Item> BREAKFAST_SUB = ITEMS.register("breakfast_sub", () -> new FoodItemBase(6,1.2F, 64) );
    public static final RegistryObject<Item> SAUSAGE_EGG_MUFFIN = ITEMS.register("sausage_egg_muffin", () -> new FoodItemBase(6,1.2F, 64) );
    public static final RegistryObject<Item> SAUSAGE_EGG_SANDWICH = ITEMS.register("sausage_egg_sandwich", () -> new FoodItemBase(6,1.2F, 64) );
    public static final RegistryObject<Item> FRIED_EGG = ITEMS.register("fried_egg", () -> new FoodItemBase(2,0.3F, 64) );
    public static final RegistryObject<Item> CHEESE_TOASTIE = ITEMS.register("cheese_toastie", () -> new FoodItemBase(2,0.3F, 64) );
    public static final RegistryObject<Item> BUTTER = ITEMS.register("butter", () -> new FoodItemBase(2,0.3F, 64) );
    public static final RegistryObject<Item> SHROOMLIGHT_SLICES = ITEMS.register("shroomlight_slices", () -> new FoodItemBase(2,0.3F, 64) );
    public static final RegistryObject<Item> RAW_WEDGES = ITEMS.register("wedges", () -> new FoodItemBase(1,0.3F, 64) );
    public static final RegistryObject<Item> ONION = ITEMS.register("onion", () -> new FoodItemBase(1,0.3F, 64) );
    public static final RegistryObject<Item> COCONUT_MEAT = ITEMS.register("coconut_meat", () -> new FoodItemBase(1,0.3F, 64) );
    public static final RegistryObject<Item> APPLE_PIE = ITEMS.register("apple_pie", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> CHEESE_PIE = ITEMS.register("cheese_pie", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> CHOCOLATE_PIE = ITEMS.register("chocolate_pie", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> LEMON_PIE = ITEMS.register("lemon_pie", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> PIE_BASE = ITEMS.register("pie_base", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> STRAWBERRY_PIE = ITEMS.register("strawberry_pie", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> PLUM_PIE = ITEMS.register("plum_pie", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> TOFFEE_PIE = ITEMS.register("toffee_pie", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> BERRY_PIE = ITEMS.register("berry_pie", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> APPLE_RASPBERRY_PIE = ITEMS.register("apple_raspberry_pie", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> WART_PIE = ITEMS.register("wart_pie", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> WEDGES_POT = ITEMS.register("wedges_pot", () -> new FoodItemBase(5,0.6F, 1) );
    public static final RegistryObject<Item> CHICKEN_PIE = ITEMS.register("chicken_pie", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> PORK_PIE = ITEMS.register("pork_pie", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> STEAK_PIE = ITEMS.register("steak_pie", () -> new FoodItemBase(8,0.3F, 64) );
    public static final RegistryObject<Item> CHICKEN_SUB = ITEMS.register("chicken_sub", () -> new FoodItemBase(8,0.8F, 64) );
    public static final RegistryObject<Item> COOKED_CHICKEN_NUGGET = ITEMS.register("cooked_chicken_nugget", () -> new MeatItem(1,0.3F, 64) );
    public static final RegistryObject<Item> COOKED_CHICKEN_PIECE = ITEMS.register("cooked_chicken_piece", () -> new MeatItem(6,0.6F, 64) );
    public static final RegistryObject<Item> COOKED_BAT_MEAT = ITEMS.register("cooked_bat_meat", () -> new MeatItem(2,0.3F, 64) );
    public static final RegistryObject<Item> COOKED_HAMBURGER_PATTY = ITEMS.register("cooked_hamburger_patty", () -> new MeatItem(8,0.8F, 64) );
    public static final RegistryObject<Item> COOKED_VEGANBURGER_PATTY = ITEMS.register("cooked_veganburger_patty", () -> new MeatItem(8,0.8F, 64) );
    public static final RegistryObject<Item> COOKED_BACON = ITEMS.register("cooked_bacon", () -> new MeatItem(8,0.8F, 64) );
    public static final RegistryObject<Item> COOKED_HOTDOG_SAUSAGE = ITEMS.register("cooked_hotdog_sausage", () -> new MeatItem(8,0.8F, 64) );
    public static final RegistryObject<Item> COOKED_SAUSAGE = ITEMS.register("cooked_sausage", () -> new MeatItem(8,0.8F, 64) );
    public static final RegistryObject<Item> COOKED_HOGLIN_MEAT = ITEMS.register("cooked_hoglin_meat", () -> new MeatItem(8,0.8F, 64) );
    public static final RegistryObject<Item> FRIED_SQUID = ITEMS.register("fried_squid", () -> new MeatItem(5,0.6F, 64) );
    public static final RegistryObject<Item> RAW_HAMBURGER_PATTY = ITEMS.register("hamburger_patty", () -> new MeatItem(8,0.8F, 64) );
    public static final RegistryObject<Item> RAW_VEGANBURGER_PATTY = ITEMS.register("veganburger_patty", () -> new MeatItem(8,0.8F, 64) );
    public static final RegistryObject<Item> RAW_BAT_MEAT = ITEMS.register("bat_meat", () -> new MeatItem(6,0.6F, 64) );
    public static final RegistryObject<Item> RAW_BACON = ITEMS.register("bacon", () -> new MeatItem(3,0.3F, 64) );
    public static final RegistryObject<Item> RAW_HOTDOG_SAUSAGE = ITEMS.register("hotdog_sausage", () -> new MeatItem(3,0.3F, 64) );
    public static final RegistryObject<Item> RAW_SAUSAGE = ITEMS.register("sausage", () -> new MeatItem(3,0.3F, 64) );
    public static final RegistryObject<Item> RAW_HOGLIN_MEAT = ITEMS.register("hoglin_meat", () -> new MeatItem(3,0.3F, 64) );
    public static final RegistryObject<Item> RAW_CHICKEN_NUGGET = ITEMS.register("chicken_nugget", () -> new MeatItem(1,0.3F, 64) );
    public static final RegistryObject<Item> RAW_SQUID = ITEMS.register("squid", () -> new MeatItem(2,0.1F, 64) );
    public static final RegistryObject<Item> ROTTEN_PORKCHOP = ITEMS.register("rotten_porkchop", () -> new FoodItemBase(4,0.1F, 64) );

    // BOWLS
    public static final RegistryObject<Item> STRAWBERRY_JELLY = ITEMS.register("strawberry_jelly", () -> new BowlItemBase(2,0.1F) );
    public static final RegistryObject<Item> CEREAL = ITEMS.register("cereal", () -> new BowlItemBase(6,0.6F) );
    public static final RegistryObject<Item> FUNGUS_STEW = ITEMS.register("fungus_stew", () -> new BowlItemBase(6,0.6F) );
    public static final RegistryObject<Item> ORANGE_JELLY = ITEMS.register("orange_jelly", () -> new BowlItemBase(2,0.1F) );
    public static final RegistryObject<Item> SPAGHETTI = ITEMS.register("spaghetti", () -> new BowlItemBase(10,0.6F) );
    public static final RegistryObject<Item> ICE_BOWL = ITEMS.register("ice_bowl", () -> new BowlItemBase(10,0.6F) );
    public static final RegistryObject<Item> RAMEN_NOODLES = ITEMS.register("ramen_noodles", () -> new BowlItemBase(10,0.6F) );
    public static final RegistryObject<Item> CUSTARD = ITEMS.register("custard", () -> new BowlItemBase(10,0.6F) );
    public static final RegistryObject<Item> RICE_PUDDING = ITEMS.register("rice_pudding", () -> new BowlItemBase(10,0.6F) );
    public static final RegistryObject<Item> NETHERWART_CHICKEN_SOUP = ITEMS.register("netherwart_chicken_soup", () -> new BowlItemBase(6,0.6F ));
    public static final RegistryObject<Item> NETHERWART_MUSHROOM_SOUP = ITEMS.register("netherwart_mushroom_soup", () -> new BowlItemBase(6,0.6F) );

    // DRINKS
    public static final RegistryObject<Item> ORANGE_JUICE = ITEMS.register("orange_juice", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> APPLE_JUICE = ITEMS.register("apple_juice", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> GRAPE_JUICE = ITEMS.register("grape_juice", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> TOMATO_JUICE = ITEMS.register("tomato_juice", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> BERRY_JUICE = ITEMS.register("berry_juice", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> STRAWBERRY_JUICE = ITEMS.register("strawberry_juice", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> MIXED_FRUIT_JUICE = ITEMS.register("mixed_fruit_juice", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> MELON_JUICE = ITEMS.register("melon_juice", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> LEMON_JUICE = ITEMS.register("lemon_juice", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> APPLE_ICECRUSH = ITEMS.register("apple_icecrush", () -> new IcecrushItem(6,0.6F) );
    public static final RegistryObject<Item> BERRY_ICECRUSH = ITEMS.register("berry_icecrush", () -> new IcecrushItem(6,0.6F) );
    public static final RegistryObject<Item> GRAPE_ICECRUSH = ITEMS.register("grape_icecrush", () -> new IcecrushItem(6,0.6F) );
    public static final RegistryObject<Item> LEMON_ICECRUSH = ITEMS.register("lemon_icecrush", () -> new IcecrushItem(6,0.6F) );
    public static final RegistryObject<Item> MELON_ICECRUSH = ITEMS.register("melon_icecrush", () -> new IcecrushItem(6,0.6F) );
    public static final RegistryObject<Item> MIXED_FRUIT_ICECRUSH = ITEMS.register("mixed_fruit_icecrush", () -> new IcecrushItem(6,0.6F) );
    public static final RegistryObject<Item> ORANGE_ICECRUSH = ITEMS.register("orange_icecrush", () -> new IcecrushItem(6,0.6F) );
    public static final RegistryObject<Item> STRAWBERRY_ICECRUSH = ITEMS.register("strawberry_icecrush", () -> new IcecrushItem(6,0.6F) );
    public static final RegistryObject<Item> APPLE_RASPBERRY_ICECRUSH = ITEMS.register("apple_raspberry_icecrush", () -> new IcecrushItem(6,0.6F) );
    public static final RegistryObject<Item> BANANA_SMOOTHIE = ITEMS.register("banana_smoothie", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> BERRY_SMOOTHIE = ITEMS.register("berry_smoothie", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> GRAPE_SMOOTHIE = ITEMS.register("grape_smoothie", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> STRAWBERRY_SMOOTHIE = ITEMS.register("strawberry_smoothie", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> RASPBERRY_SMOOTHIE = ITEMS.register("raspberry_smoothie", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> MIXED_FRUIT_SMOOTHIE = ITEMS.register("mixed_fruit_smoothie", () -> new TumblerItem(6,0.6F) );
    public static final RegistryObject<Item> CHOCOLATE_MILKSHAKE = ITEMS.register("chocolate_milkshake", () -> new BeverageCupItem(6,0.6F) );
    public static final RegistryObject<Item> STRAWBERRY_MILKSHAKE = ITEMS.register("strawberry_milkshake", () -> new BeverageCupItem(6,0.6F) );
    public static final RegistryObject<Item> BANANA_MILKSHAKE = ITEMS.register("banana_milkshake", () -> new BeverageCupItem(6,0.6F) );
    public static final RegistryObject<Item> APPLE_SODA = ITEMS.register("apple_soda", () -> new SodaCanItem(6,0.6F) );
    public static final RegistryObject<Item> BERRY_SODA = ITEMS.register("berry_soda", () -> new SodaCanItem(6,0.6F) );
    public static final RegistryObject<Item> GRAPE_SODA = ITEMS.register("grape_soda", () -> new SodaCanItem(6,0.6F) );
    public static final RegistryObject<Item> LEMON_SODA = ITEMS.register("lemon_soda", () -> new SodaCanItem(6,0.6F) );
    public static final RegistryObject<Item> ORANGE_SODA = ITEMS.register("orange_soda", () -> new SodaCanItem(6,0.6F) );
    public static final RegistryObject<Item> STRAWBERRY_SODA = ITEMS.register("strawberry_soda", () -> new SodaCanItem(6,0.6F) );
    public static final RegistryObject<Item> AMERICANO = ITEMS.register("americano", () -> new HotBeverageCupItem(6,0.6F) );
    public static final RegistryObject<Item> CAPPUCCINO = ITEMS.register("cappuccino", () -> new HotBeverageCupItem(6,0.6F) );
    public static final RegistryObject<Item> MACCHIATO = ITEMS.register("macchiato", () -> new HotBeverageCupItem(6,0.6F) );
    public static final RegistryObject<Item> MOCHA = ITEMS.register("mocha", () -> new HotBeverageCupItem(6,0.6F) );
    public static final RegistryObject<Item> TOFFEE_LATTE = ITEMS.register("toffee_latte", () -> new HotBeverageCupItem(6,0.6F) );
    public static final RegistryObject<Item> VANILLA_LATTE = ITEMS.register("vanilla_latte", () -> new HotBeverageCupItem(6,0.6F) );
    public static final RegistryObject<Item> HOT_COFFEE = ITEMS.register("hot_coffee", () -> new HotBeverageCupItem(6,0.6F) );
    public static final RegistryObject<Item> HOT_TEA = ITEMS.register("hot_tea", () -> new HotBeverageCupItem(6,0.6F) );
    public static final RegistryObject<Item> HOT_COCOA = ITEMS.register("hot_cocoa", () -> new HotBeverageCupItem(6,0.6F) );
    public static final RegistryObject<Item> VANILLA_EXTRACT = ITEMS.register("vanilla_extract", () -> new BottleItem(1,0.6F) );
    public static final RegistryObject<Item> TOMATO_KETCHUP = ITEMS.register("tomato_ketchup", () -> new BottleItem(1,0.6F) );
    public static final RegistryObject<Item> COCONUT_MILK = ITEMS.register("coconut_milk", () -> new BottleItem(6,0.6F) );
    public static final RegistryObject<Item> SPARKLING_WATER_BOTTLE = ITEMS.register("sparkling_water_bottle", () -> new GlassBottleItem(6,0.6F) );
    public static final RegistryObject<Item> CIDER = ITEMS.register("cider", () -> new TumblerItem(1,0.1F) );
    public static final RegistryObject<Item> RED_WINE = ITEMS.register("red_wine", () -> new WineGlassItem(1,0.1F) );
    public static final RegistryObject<Item> WHITE_WINE = ITEMS.register("white_wine", () -> new WineGlassItem(1,0.1F) );
    public static final RegistryObject<Item> BEER = ITEMS.register("beer", () -> new BeerGlassItem(1,0.1F) );
    public static final RegistryObject<Item> MILK_CARTON = ITEMS.register("milk_carton", () -> new CartonItem(4,1.2F) );
    public static final RegistryObject<Item> CREAM_CARTON = ITEMS.register("cream_carton", () -> new CartonItem(4,1.2F) );

    // ITEMS
    public static final RegistryObject<Item> BEER_GLASS = ITEMS.register("beer_glass", ItemBase::new);
    public static final RegistryObject<Item> CORNFLOUR = ITEMS.register("cornflour", ItemBase::new);
    public static final RegistryObject<Item> BEVERAGE_CUP = ITEMS.register("beverage_cup", ItemBase::new);
    public static final RegistryObject<Item> BOTTLE = ITEMS.register("bottle", ItemBase::new);
    public static final RegistryObject<Item> BOTTLED_BEER = ITEMS.register("bottled_beer", ItemBase::new);
    public static final RegistryObject<Item> BOTTLED_CIDER = ITEMS.register("bottled_cider", ItemBase::new);
    public static final RegistryObject<Item> BOTTLED_RED_WINE = ITEMS.register("bottled_red_wine", ItemBase::new);
    public static final RegistryObject<Item> BOTTLED_WHITE_WINE = ITEMS.register("bottled_white_wine", ItemBase::new);
    public static final RegistryObject<Item> CARTON = ITEMS.register("carton", ItemBase::new);
    public static final RegistryObject<Item> CHICKEN_SELECT_BOX = ITEMS.register("chicken_select_box", ItemBase::new);
    public static final RegistryObject<Item> EMPTY_ICECRUSH_GLASS = ITEMS.register("empty_icecrush_glass", ItemBase::new);
    public static final RegistryObject<Item> EMPTY_POPCORN_BUCKET = ITEMS.register("empty_popcorn_bucket", ItemBase::new);
    public static final RegistryObject<Item> EMPTY_TUMBLER_GLASS = ITEMS.register("empty_tumbler_glass", ItemBase::new);
    public static final RegistryObject<Item> EMPTY_WEDGES_POT = ITEMS.register("empty_wedges_pot", ItemBase::new);
    public static final RegistryObject<Item> FRY_WRAPPER = ITEMS.register("fry_wrapper", ItemBase::new);
    public static final RegistryObject<Item> HOT_BEVERAGE_CUP = ITEMS.register("hot_beverage_cup", ItemBase::new);
    public static final RegistryObject<Item> ICING = ITEMS.register("icing", ItemBase::new);
    public static final RegistryObject<Item> JAR = ITEMS.register("jar", ItemBase::new);
    public static final RegistryObject<Item> SODA_CAN_EMPTY = ITEMS.register("soda_can_empty", ItemBase::new);
    public static final RegistryObject<Item> STARCH = ITEMS.register("starch", ItemBase::new);
    public static final RegistryObject<Item> WINE_GLASS = ITEMS.register("wine_glass", ItemBase::new);
    public static final RegistryObject<Item> SUB_WRAPPER = ITEMS.register("sub_wrapper", ItemBase::new);

    // TOOLS
    // tier, attackDamage, attackSpeed
    public static final RegistryObject<Item> WOODEN_KNIFE = ITEMS.register("wooden_knife", () -> new SwordItem(Tiers.WOOD, 3, 0, new Item.Properties().tab(MoreFood.TAB)));
    public static final RegistryObject<Item> GOLDEN_KNIFE = ITEMS.register("golden_knife", () -> new SwordItem(Tiers.GOLD, 3, 0, new Item.Properties().tab(MoreFood.TAB)));
    public static final RegistryObject<Item> STONE_KNIFE = ITEMS.register("stone_knife", () -> new SwordItem(Tiers.STONE, 3, 0, new Item.Properties().tab(MoreFood.TAB)));
    public static final RegistryObject<Item> COPPER_KNIFE = ITEMS.register("copper_knife", () -> new SwordItem(Tiers.STONE, 3, 0, new Item.Properties().tab(MoreFood.TAB)));
    public static final RegistryObject<Item> IRON_KNIFE = ITEMS.register("iron_knife", () -> new SwordItem(Tiers.IRON, 3, 0, new Item.Properties().tab(MoreFood.TAB)));
    public static final RegistryObject<Item> DIAMOND_KNIFE = ITEMS.register("diamond_knife", () -> new SwordItem(Tiers.DIAMOND, 3, 0, new Item.Properties().tab(MoreFood.TAB)));
    public static final RegistryObject<Item> NETHERITE_KNIFE = ITEMS.register("netherite_knife", () -> new SwordItem(Tiers.NETHERITE, 3, 0, new Item.Properties().tab(MoreFood.TAB)));
    public static final RegistryObject<Item> WOODEN_SPOON = ITEMS.register("wooden_spoon", () -> new ShovelItem(Tiers.WOOD, 0, -3, new Item.Properties().tab(MoreFood.TAB)));
}