give @s morefood:lime_candle_redwhiteblue_cake
give @s morefood:magenta_candle_chocolate_cake
give @s morefood:magenta_candle_pound_cake
give @s morefood:magenta_candle_rainbow_cake
give @s morefood:magenta_candle_redwhiteblue_cake
give @s morefood:orange_candle_chocolate_cake
give @s morefood:orange_candle_pound_cake
give @s morefood:orange_candle_rainbow_cake
give @s morefood:orange_candle_redwhiteblue_cake
give @s morefood:pink_candle_chocolate_cake
give @s morefood:pink_candle_pound_cake
give @s morefood:pink_candle_rainbow_cake
give @s morefood:pink_candle_redwhiteblue_cake
give @s morefood:purple_candle_chocolate_cake
give @s morefood:purple_candle_pound_cake
give @s morefood:purple_candle_rainbow_cake
give @s morefood:purple_candle_redwhiteblue_cake
give @s morefood:red_candle_chocolate_cake
give @s morefood:red_candle_pound_cake
give @s morefood:red_candle_rainbow_cake
give @s morefood:red_candle_redwhiteblue_cake
give @s morefood:white_candle_chocolate_cake
give @s morefood:white_candle_pound_cake
give @s morefood:white_candle_rainbow_cake
give @s morefood:white_candle_redwhiteblue_cake
give @s morefood:yellow_candle_chocolate_cake
give @s morefood:yellow_candle_pound_cake
give @s morefood:yellow_candle_rainbow_cake
give @s morefood:yellow_candle_redwhiteblue_cake
give @s morefood:chocolate_cake_block
give @s morefood:coffee_bush
give @s morefood:apple_block
give @s morefood:baked_potato_block
give @s morefood:beef_block
give @s morefood:carrot_block
give @s morefood:chicken_block
