give @s morefood:grape_beverage_powder
give @s morefood:guacamole
give @s morefood:hash_browns
give @s morefood:jalapeno_cheese_bucket
give @s morefood:jalapeno_cheese_pie
give @s morefood:jalapeno_cheese_spread
give @s morefood:jalapeno_cheese_toastie
give @s morefood:jalapeno_cheese_wedge
give @s morefood:jalapeno_round_cheese
give @s morefood:large_bowl
give @s morefood:lemon_lime_beverage_powder
give @s morefood:maple_muffin
give @s morefood:maple_sap_bucket
give @s morefood:maple_syrup
give @s morefood:maple_syrup_bucket
give @s morefood:marshmallow
give @s morefood:marshmallow_on_a_stick
give @s morefood:mashed_potatoes
give @s morefood:meal_ready_to_eat
give @s morefood:milk_chocolate_covered_apple
give @s morefood:oatmeal
give @s morefood:oatmeal_cookie
give @s morefood:oats
give @s morefood:oat_seeds
give @s morefood:onion_rings
give @s morefood:orange_beverage_powder
give @s morefood:pancake_mix
give @s morefood:peanut
give @s morefood:peanut_butter
give @s morefood:peanut_butter_jelly_sandwich
give @s morefood:peanut_seeds
give @s morefood:peppermint
give @s morefood:peppermint_extract
give @s morefood:peppermint_ring
give @s morefood:peppermint_seeds
give @s morefood:poisonous_sweet_potato
