give @s morefood:lime_candle_redwhiteblue_cake
give @s morefood:magenta_candle_chocolate_cake
give @s morefood:magenta_candle_pound_cake
give @s morefood:magenta_candle_rainbow_cake
give @s morefood:magenta_candle_redwhiteblue_cake
give @s morefood:orange_candle_chocolate_cake
give @s morefood:orange_candle_pound_cake
give @s morefood:orange_candle_rainbow_cake
give @s morefood:orange_candle_redwhiteblue_cake
give @s morefood:pink_candle_chocolate_cake
give @s morefood:pink_candle_pound_cake
give @s morefood:pink_candle_rainbow_cake
give @s morefood:pink_candle_redwhiteblue_cake
give @s morefood:purple_candle_chocolate_cake
give @s morefood:purple_candle_pound_cake
give @s morefood:purple_candle_rainbow_cake
give @s morefood:purple_candle_redwhiteblue_cake
give @s morefood:red_candle_chocolate_cake
give @s morefood:red_candle_pound_cake
give @s morefood:red_candle_rainbow_cake
give @s morefood:red_candle_redwhiteblue_cake
give @s morefood:white_candle_chocolate_cake
give @s morefood:white_candle_pound_cake
give @s morefood:white_candle_rainbow_cake
give @s morefood:white_candle_redwhiteblue_cake
give @s morefood:yellow_candle_chocolate_cake
give @s morefood:yellow_candle_pound_cake
give @s morefood:yellow_candle_rainbow_cake
give @s morefood:yellow_candle_redwhiteblue_cake
give @s morefood:chocolate_cake_block
give @s morefood:coffee_bush
give @s morefood:apple_block
give @s morefood:baked_potato_block
give @s morefood:beef_block
give @s morefood:carrot_block
give @s morefood:chicken_block
give @s morefood:poison_berry_bush
give @s morefood:poison_berry_sack
give @s morefood:raspberry_sack
give @s morefood:raspberry_seed_sack
give @s morefood:rice_sack
give @s morefood:rice_seed_sack
give @s morefood:soybean_bush
give @s morefood:soybean_sack
give @s morefood:spinach_crop
give @s morefood:spinach_sack
give @s morefood:spinach_seed_sack
give @s morefood:strawberry_sack
give @s morefood:strawberry_seed_sack
give @s morefood:sugar_cookie_sack
give @s morefood:sweet_potatoes
give @s morefood:sweet_potato_sack
give @s morefood:tea_leaf_sack
give @s morefood:tea_seed_sack
give @s morefood:tomato_sack
give @s morefood:tomato_seed_sack
give @s morefood:vanilla_pod_sack
give @s morefood:vanilla_seed_sack
give @s morefood:yeast_sack
give @s morefood:almond_sapling_block
give @s morefood:bean_bush
give @s morefood:cranberry_bush
give @s morefood:fertile_soil
give @s morefood:garlic_crop
give @s morefood:peppermint_bush
give @s morefood:spearmint_plant
give @s morefood:watermint_plant
give @s morefood:potted_almond_sapling
give @s morefood:potted_apple_sapling
give @s morefood:potted_avocado_sapling
give @s morefood:potted_banana_sapling
give @s morefood:potted_lemon_sapling
