give @s morefood:apple_sapling_block
give @s morefood:banana_sapling_block
give @s morefood:barley_crop
give @s morefood:cake_with_cherries_block
give @s morefood:black_candle_cake_with_cherries
give @s morefood:black_candle_chocolate_cake
give @s morefood:black_candle_pound_cake
give @s morefood:black_candle_rainbow_cake
give @s morefood:black_candle_redwhiteblue_cake
give @s morefood:blue_candle_cake_with_cherries
give @s morefood:blue_candle_chocolate_cake
give @s morefood:blue_candle_pound_cake
give @s morefood:blue_candle_rainbow_cake
give @s morefood:blue_candle_redwhiteblue_cake
give @s morefood:brown_candle_cake_with_cherries
give @s morefood:brown_candle_chocolate_cake
give @s morefood:brown_candle_pound_cake
give @s morefood:brown_candle_rainbow_cake
give @s morefood:brown_candle_redwhiteblue_cake
give @s morefood:candle_cake_with_cherries
give @s morefood:candle_chocolate_cake
give @s morefood:candle_pound_cake
give @s morefood:candle_rainbow_cake
give @s morefood:candle_redwhiteblue_cake
give @s morefood:cyan_candle_cake_with_cherries
give @s morefood:cyan_candle_chocolate_cake
give @s morefood:cyan_candle_pound_cake
give @s morefood:cyan_candle_rainbow_cake
give @s morefood:cyan_candle_redwhiteblue_cake
give @s morefood:gray_candle_cake_with_cherries
give @s morefood:gray_candle_chocolate_cake
give @s morefood:gray_candle_pound_cake
give @s morefood:gray_candle_rainbow_cake
give @s morefood:gray_candle_redwhiteblue_cake
give @s morefood:green_candle_cake_with_cherries
give @s morefood:green_candle_chocolate_cake
