give @s morefood:black_candle_redwhiteblue_cake
give @s morefood:blue_candle_chocolate_cake
give @s morefood:blue_candle_pound_cake
give @s morefood:blue_candle_rainbow_cake
give @s morefood:blue_candle_redwhiteblue_cake
give @s morefood:brown_candle_chocolate_cake
give @s morefood:brown_candle_pound_cake
give @s morefood:brown_candle_rainbow_cake
give @s morefood:brown_candle_redwhiteblue_cake
give @s morefood:candle_chocolate_cake
give @s morefood:candle_pound_cake
give @s morefood:candle_rainbow_cake
give @s morefood:candle_redwhiteblue_cake
give @s morefood:cyan_candle_chocolate_cake
give @s morefood:cyan_candle_pound_cake
give @s morefood:cyan_candle_rainbow_cake
give @s morefood:cyan_candle_redwhiteblue_cake
give @s morefood:gray_candle_chocolate_cake
give @s morefood:gray_candle_pound_cake
give @s morefood:gray_candle_rainbow_cake
give @s morefood:gray_candle_redwhiteblue_cake
give @s morefood:green_candle_chocolate_cake
give @s morefood:green_candle_pound_cake
give @s morefood:green_candle_rainbow_cake
give @s morefood:green_candle_redwhiteblue_cake
give @s morefood:light_blue_candle_chocolate_cake
give @s morefood:light_blue_candle_pound_cake
give @s morefood:light_blue_candle_rainbow_cake
give @s morefood:light_blue_candle_redwhiteblue_cake
give @s morefood:light_gray_candle_chocolate_cake
give @s morefood:light_gray_candle_pound_cake
give @s morefood:light_gray_candle_rainbow_cake
give @s morefood:light_gray_candle_redwhiteblue_cake
give @s morefood:lime_candle_chocolate_cake
give @s morefood:lime_candle_pound_cake
give @s morefood:lime_candle_rainbow_cake
give @s morefood:chocolate_chunk_oatmeal_cookie_sack
give @s morefood:coconut_sack
give @s morefood:coffee_bean_sack
give @s morefood:corn_cob_sack
give @s morefood:corn_starch_sack
give @s morefood:cranberry_sack
give @s morefood:eggplant_bush
give @s morefood:eggplant_sack
give @s morefood:eggplant_seed_sack
give @s morefood:flour_sack
give @s morefood:garlic_sack
give @s morefood:gherkin_sack
give @s morefood:gherkin_seed_sack
give @s morefood:grape_sack
give @s morefood:grape_seed_sack
give @s morefood:hops_sack
give @s morefood:hops_seed_sack
give @s morefood:lemon_sack
give @s morefood:lettuce_sack
give @s morefood:lettuce_seed_sack
give @s morefood:nether_cookie_sack
give @s morefood:oatmeal_cookie_sack
give @s morefood:oat_crop
give @s morefood:oat_sack
give @s morefood:oat_seed_sack
give @s morefood:olive_sack
give @s morefood:onion_sack
give @s morefood:onion_seed_sack
give @s morefood:orange_sack
give @s morefood:peanut_crop
give @s morefood:peanut_sack
give @s morefood:peanut_seed_sack
give @s morefood:pepper_sack
give @s morefood:pepper_seed_sack
give @s morefood:plum_sack
give @s morefood:poisonous_sweet_potato_sack
