give @s morefood:pepper_seed_sack
give @s morefood:plum_sack
give @s morefood:poisonous_sweet_potato_sack
give @s morefood:poison_berry_sack
give @s morefood:raspberry_sack
give @s morefood:raspberry_seed_sack
give @s morefood:rice_sack
give @s morefood:rice_seed_sack
give @s morefood:soybean_sack
give @s morefood:spinach_sack
give @s morefood:spinach_seed_sack
give @s morefood:strawberry_sack
give @s morefood:strawberry_seed_sack
give @s morefood:sugar_cookie_sack
give @s morefood:sweet_potato_sack
give @s morefood:tea_leaf_sack
give @s morefood:tea_seed_sack
give @s morefood:tomato_sack
give @s morefood:tomato_seed_sack
give @s morefood:vanilla_pod_sack
give @s morefood:vanilla_seed_sack
give @s morefood:yeast_sack
give @s morefood:soybean_bush
give @s morefood:spearmint_plant
give @s morefood:spinach_crop
give @s morefood:sweet_potatoes
give @s morefood:watermint_plant
give @s morefood:wooden_tree_tap
give @s morefood:apple_hanging_fruit
give @s morefood:apple_sapling_block
give @s morefood:banana_hanging_fruit
give @s morefood:banana_sapling_block
give @s morefood:barley_crop
give @s morefood:black_candle_chocolate_cake
give @s morefood:black_candle_pound_cake
give @s morefood:black_candle_rainbow_cake
give @s morefood:squid_block
give @s morefood:white_chocolate_block
give @s morefood:gherkin_bush
give @s morefood:grape_bush
give @s morefood:hops_crop
give @s morefood:apple_hanging_fruit
give @s morefood:banana_hanging_fruit
give @s morefood:corn_crop
give @s morefood:corn_sack
give @s morefood:lemon_hanging_fruit
give @s morefood:olives_hanging_fruit
give @s morefood:orange_hanging_fruit
give @s morefood:plum_hanging_fruit
give @s morefood:lemon_sapling_block
give @s morefood:lettuce_crop
give @s morefood:olive_sapling_block
give @s morefood:onion_crop
give @s morefood:orange_sapling_block
give @s morefood:palm_sapling_block
give @s morefood:pepper_bush
give @s morefood:plum_sapling_block
give @s morefood:pound_cake_block
give @s morefood:almond_sack
give @s morefood:avocado_sack
give @s morefood:avocado_sapling_block
give @s morefood:banana_sack
give @s morefood:barley_seed_sack
give @s morefood:bean_sack
give @s morefood:blueberry_bush
give @s morefood:blueberry_sack
give @s morefood:blueberry_seed_sack
give @s morefood:buckwheat_crop
give @s morefood:buckwheat_sack
give @s morefood:cabbage_crop
give @s morefood:cabbage_sack
give @s morefood:cabbage_seed_sack
