give @s morefood:almond_sapling_block
give @s morefood:avocado_sapling_block
give @s morefood:bean_bush
give @s morefood:blueberry_bush
give @s morefood:buckwheat_crop
give @s morefood:cabbage_crop
give @s morefood:cranberry_bush
give @s morefood:eggplant_bush
give @s morefood:fertile_soil
give @s morefood:garlic_crop
give @s morefood:hanging_almond
give @s morefood:hanging_avocado
give @s morefood:oat_crop
give @s morefood:peanut_crop
give @s morefood:peppermint_bush
give @s morefood:poison_berry_bush
give @s morefood:almond_sack
give @s morefood:avocado_sack
give @s morefood:banana_sack
give @s morefood:barley_seed_sack
give @s morefood:bean_sack
give @s morefood:green_candle_pound_cake
give @s morefood:green_candle_rainbow_cake
give @s morefood:green_candle_redwhiteblue_cake
give @s morefood:light_blue_candle_cake_with_cherries
give @s morefood:light_blue_candle_chocolate_cake
give @s morefood:light_blue_candle_pound_cake
give @s morefood:light_blue_candle_rainbow_cake
give @s morefood:light_blue_candle_redwhiteblue_cake
give @s morefood:light_gray_candle_cake_with_cherries
give @s morefood:light_gray_candle_chocolate_cake
give @s morefood:light_gray_candle_pound_cake
give @s morefood:light_gray_candle_rainbow_cake
give @s morefood:light_gray_candle_redwhiteblue_cake
give @s morefood:lime_candle_cake_with_cherries
give @s morefood:lime_candle_chocolate_cake
give @s morefood:lime_candle_pound_cake
give @s morefood:lime_candle_rainbow_cake
give @s morefood:lime_candle_redwhiteblue_cake
give @s morefood:magenta_candle_cake_with_cherries
give @s morefood:magenta_candle_chocolate_cake
give @s morefood:magenta_candle_pound_cake
give @s morefood:magenta_candle_rainbow_cake
give @s morefood:magenta_candle_redwhiteblue_cake
give @s morefood:orange_candle_cake_with_cherries
give @s morefood:orange_candle_chocolate_cake
give @s morefood:orange_candle_pound_cake
give @s morefood:orange_candle_rainbow_cake
give @s morefood:orange_candle_redwhiteblue_cake
give @s morefood:pink_candle_cake_with_cherries
give @s morefood:pink_candle_chocolate_cake
give @s morefood:pink_candle_pound_cake
give @s morefood:pink_candle_rainbow_cake
give @s morefood:pink_candle_redwhiteblue_cake
give @s morefood:purple_candle_cake_with_cherries
give @s morefood:purple_candle_chocolate_cake
give @s morefood:purple_candle_pound_cake
