give @s morefood:blueberry_sack
give @s morefood:blueberry_seed_sack
give @s morefood:buckwheat_sack
give @s morefood:cabbage_sack
give @s morefood:cabbage_seed_sack
give @s morefood:chocolate_chunk_oatmeal_cookie_sack
give @s morefood:coconut_sack
give @s morefood:coffee_bean_sack
give @s morefood:corn_starch_sack
give @s morefood:corn_cob_sack
give @s morefood:corn_sack
give @s morefood:cranberry_sack
give @s morefood:eggplant_sack
give @s morefood:eggplant_seed_sack
give @s morefood:flour_sack
give @s morefood:garlic_sack
give @s morefood:gherkin_sack
give @s morefood:gherkin_seed_sack
give @s morefood:grape_sack
give @s morefood:grape_seed_sack
give @s morefood:hops_sack
give @s morefood:hops_seed_sack
give @s morefood:lemon_sack
give @s morefood:lettuce_sack
give @s morefood:lettuce_seed_sack
give @s morefood:nether_cookie_sack
give @s morefood:oatmeal_cookie_sack
give @s morefood:oat_sack
give @s morefood:oat_seed_sack
give @s morefood:olive_sack
give @s morefood:onion_sack
give @s morefood:onion_seed_sack
give @s morefood:orange_sack
give @s morefood:peanut_sack
give @s morefood:peanut_seed_sack
give @s morefood:pepper_sack
give @s morefood:purple_candle_rainbow_cake
give @s morefood:purple_candle_redwhiteblue_cake
give @s morefood:red_candle_cake_with_cherries
give @s morefood:red_candle_chocolate_cake
give @s morefood:red_candle_pound_cake
give @s morefood:red_candle_rainbow_cake
give @s morefood:red_candle_redwhiteblue_cake
give @s morefood:white_candle_cake_with_cherries
give @s morefood:white_candle_chocolate_cake
give @s morefood:white_candle_pound_cake
give @s morefood:white_candle_rainbow_cake
give @s morefood:white_candle_redwhiteblue_cake
give @s morefood:yellow_candle_cake_with_cherries
give @s morefood:yellow_candle_chocolate_cake
give @s morefood:yellow_candle_pound_cake
give @s morefood:yellow_candle_rainbow_cake
give @s morefood:yellow_candle_redwhiteblue_cake
give @s morefood:chocolate_cake_block
give @s morefood:coffee_bush
give @s morefood:apple_block
give @s morefood:baked_potato_block
give @s morefood:beef_block
give @s morefood:carrot_block
give @s morefood:chicken_block
give @s morefood:cooked_beef_block
give @s morefood:cooked_chicken_block
give @s morefood:cooked_mutton_block
give @s morefood:cooked_rabbit_block
give @s morefood:cooked_squid_block
give @s morefood:cookie_block
give @s morefood:dark_chocolate_block
give @s morefood:golden_apple_block
give @s morefood:milk_chocolate_block
give @s morefood:mutton_block
give @s morefood:potato_block
give @s morefood:rabbit_block
