give @s morefood:almonds
give @s morefood:almond_sapling
give @s morefood:apple_sauce
give @s morefood:avocado
give @s morefood:avocado_sapling
give @s morefood:beans
give @s morefood:bean_seeds
give @s morefood:beef_goulash
give @s morefood:beef_ravioli
give @s morefood:beef_stew
give @s morefood:blueberries
give @s morefood:blueberry_seeds
give @s morefood:blueberry_syrup
give @s morefood:breadsticks
give @s morefood:breadsticks_with_glowberry_jam
give @s morefood:breadsticks_with_jam
give @s morefood:breadsticks_with_peanut_butter
give @s morefood:buckwheat
give @s morefood:burnt_marshmallow_on_a_stick
give @s morefood:cabbage
give @s morefood:cabbage_seeds
give @s morefood:cappuccino_drink_mix
give @s morefood:cheese_spread
give @s morefood:cheese_tortellini
give @s morefood:chicken_soup
give @s morefood:chili
give @s morefood:chocolate_banana_muffin
give @s morefood:chocolate_chunk_oatmeal_cookie
give @s morefood:chocolate_peanut_butter
give @s morefood:chocolate_protein_drink_mix
give @s morefood:chocolate_pudding
give @s morefood:cocoa_beverage_powder
give @s morefood:cooked_marshmallow_on_a_stick
give @s morefood:cornbread
give @s morefood:crackers
give @s morefood:crackers_with_cheese
give @s morefood:bacon
give @s morefood:bacon_egg_muffin
give @s morefood:bacon_egg_sandwich
give @s morefood:baked_sweet_potato
give @s morefood:banana
give @s morefood:barley_seeds
give @s morefood:bat_meat
give @s morefood:beverage_cup
give @s morefood:blue_cupcake
give @s morefood:bottle
give @s morefood:bread_loaf
give @s morefood:burger_bun
give @s morefood:burrito
give @s morefood:butter
give @s morefood:cereal
give @s morefood:cheese_bucket
give @s morefood:cheese_toastie
give @s morefood:cheese_wedge
give @s morefood:chicken_fajita
give @s morefood:chicken_nugget
give @s morefood:chicken_select
give @s morefood:chicken_select_box
give @s morefood:chocolate_cake
give @s morefood:coconut
give @s morefood:coconut_meat
give @s morefood:coffee_beans
give @s morefood:cooked_bacon
give @s morefood:cooked_bat_meat
give @s morefood:cooked_chicken_nugget
give @s morefood:cooked_chicken_piece
give @s morefood:hamburger_patty
give @s morefood:cooked_hoglin_meat
give @s morefood:copper_knife
give @s morefood:creative_hunger
give @s morefood:custard
give @s morefood:dark_chocolate
