give @s morefood:bacon_egg_muffin
give @s morefood:bacon_egg_sandwich
give @s morefood:baked_sweet_potato
give @s morefood:banana
give @s morefood:banana_sapling
give @s morefood:barley_seeds
give @s morefood:bat_meat
give @s morefood:beef_submarine_sandwich
give @s morefood:beer_mug
give @s morefood:beverage_cup
give @s morefood:blue_cupcake
give @s morefood:bottle
give @s morefood:bread_loaf
give @s morefood:breakfast_submarine_sandwich
give @s morefood:burger_bun
give @s morefood:burrito
give @s morefood:butter
give @s morefood:cereal
give @s morefood:cheese_bucket
give @s morefood:cheese_toastie
give @s morefood:cheese_wedge
give @s morefood:chicken_fajita
give @s morefood:chicken_nugget
give @s morefood:chicken_select
give @s morefood:chicken_select_box
give @s morefood:chicken_submarine_sandwich
give @s morefood:chocolate_cake
give @s morefood:coconut
give @s morefood:coconut_meat
give @s morefood:coffee_beans
give @s morefood:cooked_bacon
give @s morefood:cooked_bat_meat
give @s morefood:cooked_chicken_nugget
give @s morefood:cooked_chicken_piece
give @s morefood:hamburger_patty
give @s morefood:icecrush_apple
give @s morefood:icecrush_apple_raspberry
give @s morefood:icecrush_berry
give @s morefood:icecrush_grape
give @s morefood:icecrush_lemon
give @s morefood:icecrush_melon
give @s morefood:icecrush_mixed_fruit
give @s morefood:icecrush_orange
give @s morefood:icecrush_strawberry
give @s morefood:ice_bowl
give @s morefood:jalapeno_round_cheese
give @s morefood:juice_apple
give @s morefood:juice_berry
give @s morefood:juice_grape
give @s morefood:juice_lemon
give @s morefood:juice_melon
give @s morefood:juice_mixed_fruit
give @s morefood:juice_orange
give @s morefood:juice_strawberry
give @s morefood:juice_tomato
give @s morefood:milkshake_banana
give @s morefood:milkshake_chocolate
give @s morefood:milkshake_strawberry
give @s morefood:milk_carton
give @s morefood:pie_apple
give @s morefood:pie_apple_raspberry
give @s morefood:pie_base
give @s morefood:pie_berry
give @s morefood:pie_cheese
give @s morefood:pie_chicken
give @s morefood:pie_chocolate
give @s morefood:pie_lemon
give @s morefood:pie_plum
give @s morefood:pie_pork
give @s morefood:pie_steak
give @s morefood:pie_strawberry
