give @s morefood:bottled_red_wine
give @s morefood:bottled_red_wine_25
give @s morefood:bottled_red_wine_50
give @s morefood:bottled_red_wine_75
give @s morefood:bottled_white_wine_0
give @s morefood:bottled_white_wine
give @s morefood:bottled_white_wine_25
give @s morefood:bottled_white_wine_50
give @s morefood:bottled_white_wine_75
give @s morefood:cappuccino
give @s morefood:cider
give @s morefood:coconut_milk
give @s morefood:cream_bottle
give @s morefood:hot_cocoa
give @s morefood:hot_coffee
give @s morefood:hot_tea
give @s morefood:apple_ice_crush
give @s morefood:apple_raspberry_ice_crush
give @s morefood:berry_ice_crush
give @s morefood:grape_ice_crush
give @s morefood:lemon_ice_crush
give @s morefood:melon_ice_crush
give @s morefood:mixed_fruit_ice_crush
give @s morefood:strawberry_ice_crush
give @s morefood:orange_ice_crush
give @s morefood:apple_juice
give @s morefood:berry_juice
give @s morefood:grape_juice
give @s morefood:lemon_juice
give @s morefood:melon_juice
give @s morefood:mixed_fruit_juice
give @s morefood:orange_juice
give @s morefood:strawberry_juice
give @s morefood:tomato_juice
give @s morefood:macchiato
give @s morefood:banana_milkshake
give @s morefood:noodles
give @s morefood:olives
give @s morefood:onigiri
give @s morefood:onion
give @s morefood:onion_seeds
give @s morefood:orange
give @s morefood:orange_jelly
give @s morefood:pancakes
give @s morefood:pasta
give @s morefood:pepper
give @s morefood:pepper_seeds
give @s morefood:pickles
give @s morefood:pink_cupcake
give @s morefood:pitta_bread
give @s morefood:pizza
give @s morefood:pizza_slice
give @s morefood:plum
give @s morefood:popcorn
give @s morefood:popcorn_bucket
give @s morefood:almonds
give @s morefood:avocado
give @s morefood:beans
give @s morefood:beef_goulash
give @s morefood:beef_ravioli
give @s morefood:beef_stew
give @s morefood:blueberries
give @s morefood:blueberry_seeds
give @s morefood:blueberry_syrup
give @s morefood:breadsticks
give @s morefood:breadsticks_with_glowberry_jam
give @s morefood:breadsticks_with_jam
give @s morefood:breadsticks_with_peanut_butter
give @s morefood:buckwheat
give @s morefood:burnt_marshmallow_on_a_stick
give @s morefood:cabbage
give @s morefood:cabbage_seeds
