give @s morefood:cooked_hoglin_meat
give @s morefood:cooked_frankfurter_sausage
give @s morefood:cooked_breakfast_sausage
give @s morefood:veggie_burger_patty
give @s morefood:cooked_potato_wedges
give @s morefood:copper_knife
give @s morefood:corn
give @s morefood:corn_starch
give @s morefood:corncob
give @s morefood:creative_hunger
give @s morefood:custard
give @s morefood:bread_slice
give @s morefood:french_fries
give @s morefood:dark_chocolate
give @s morefood:knife_diamond
give @s morefood:chocolate_doughnut
give @s morefood:coffee_doughnut
give @s morefood:iced_doughnut
give @s morefood:pink_ice_doughnut
give @s morefood:plain_doughnut
give @s morefood:strawberry_doughnut
give @s morefood:toffee_doughnut
give @s morefood:dough
give @s morefood:americano
give @s morefood:beer
give @s morefood:bottled_beer_0
give @s morefood:bottled_beer
give @s morefood:bottled_beer_25
give @s morefood:bottled_beer_50
give @s morefood:bottled_beer_75
give @s morefood:bottled_cider_0
give @s morefood:bottled_cider
give @s morefood:bottled_cider_25
give @s morefood:bottled_cider_50
give @s morefood:bottled_cider_75
give @s morefood:bottled_red_wine_0
give @s morefood:pie_toffee
give @s morefood:pizza_base
give @s morefood:raw_hamburger_patty
give @s morefood:raw_sausage
give @s morefood:raw_squid
give @s morefood:raw_wedges
give @s morefood:round_cheese
give @s morefood:shroomlight_slices
give @s morefood:smoothie_banana
give @s morefood:smoothie_berry
give @s morefood:smoothie_grape
give @s morefood:smoothie_mixed_fruit
give @s morefood:smoothie_raspberry
give @s morefood:smoothie_strawberry
give @s morefood:soda_apple
give @s morefood:soda_berry
give @s morefood:soda_can_empty
give @s morefood:soda_grape
give @s morefood:soda_lemon
give @s morefood:soda_orange
give @s morefood:soda_strawberry
give @s morefood:sub_bun
give @s morefood:sweet_potato_fries
give @s morefood:veganburger
give @s morefood:raw_veganburger_patty
give @s morefood:wedges_pot
give @s morefood:lemon
give @s morefood:lettuce
give @s morefood:lettuce_seeds
give @s morefood:milk_chocolate
give @s morefood:muffin_bun
give @s morefood:netherite_apple
give @s morefood:knife_netherite
give @s morefood:netherwart_chicken_soup
give @s morefood:netherwart_mushroom_soup
give @s morefood:nether_cookie
