give @s morefood:grape_beverage_powder
give @s morefood:guacamole
give @s morefood:hash_browns
give @s morefood:jalapeno_cheese_bucket
give @s morefood:jalapeno_cheese_pie
give @s morefood:jalapeno_cheese_spread
give @s morefood:jalapeno_cheese_toastie
give @s morefood:jalapeno_cheese_wedge
give @s morefood:truckle_of_jalapeno_cheese
give @s morefood:large_bowl
give @s morefood:lemon_lime_beverage_powder
give @s morefood:maple_muffin
give @s morefood:maple_sap_bucket
give @s morefood:maple_syrup
give @s morefood:maple_syrup_bucket
give @s morefood:marshmallow
give @s morefood:marshmallow_on_a_stick
give @s morefood:mashed_potatoes
give @s morefood:meal_ready_to_eat
give @s morefood:milk_chocolate_covered_apple
give @s morefood:oatmeal
give @s morefood:oatmeal_cookie
give @s morefood:oats
give @s morefood:oat_seeds
give @s morefood:onion_rings
give @s morefood:orange_beverage_powder
give @s morefood:pancake_mix
give @s morefood:peanut
give @s morefood:peanut_butter
give @s morefood:peanut_butter_jelly_sandwich
give @s morefood:peanut_seeds
give @s morefood:peppermint
give @s morefood:peppermint_extract
give @s morefood:peppermint_ring
give @s morefood:peppermint_seeds
give @s morefood:poisonous_sweet_potato
give @s morefood:red_wine
give @s morefood:sparkling_water_bottle
give @s morefood:toffee_latte
give @s morefood:vanilla_extract
give @s morefood:vanilla_latte
give @s morefood:white_wine
give @s morefood:flour
give @s morefood:fried_egg
give @s morefood:fried_squid
give @s morefood:fry_wrapper
give @s morefood:fungus_stew
give @s morefood:gelatin
give @s morefood:gherkin
give @s morefood:gherkin_seeds
give @s morefood:knife_golden
give @s morefood:grape
give @s morefood:grape_seeds
give @s morefood:hamburger
give @s morefood:hoglin_meat
give @s morefood:hops
give @s morefood:hops_seeds
give @s morefood:hot_beverage_cup
give @s morefood:icing
give @s morefood:knife_iron
give @s morefood:jam
give @s morefood:jar
give @s morefood:jelly_sandwich
give @s morefood:kebab
give @s morefood:ketchup
give @s morefood:applesauce
give @s morefood:beef_sub
give @s morefood:beer_glass
give @s morefood:breakfast_sub
give @s morefood:chicken_sub
give @s morefood:cooked_hotdog_sausage
give @s morefood:cooked_sausage
