give @s morefood:chocolate_milkshake
give @s morefood:strawberry_milkshake
give @s morefood:milk_bottle
give @s morefood:mocha
give @s morefood:oil
give @s morefood:red_wine
give @s morefood:banana_smoothie
give @s morefood:berry_smoothie
give @s morefood:grape_smoothie
give @s morefood:mixed_fruit_smoothie
give @s morefood:raspberry_smoothie
give @s morefood:strawberry_smoothie
give @s morefood:apple_soda
give @s morefood:berry_soda
give @s morefood:grape_soda
give @s morefood:lemon_soda
give @s morefood:orange_soda
give @s morefood:strawberry_soda
give @s morefood:sparkling_water_bottle
give @s morefood:toffee_latte
give @s morefood:vanilla_extract
give @s morefood:vanilla_latte
give @s morefood:white_wine
give @s morefood:ice_crush_glass
give @s morefood:tumbler_glass
give @s morefood:flour
give @s morefood:fried_egg
give @s morefood:fried_squid
give @s morefood:french_fry_pot
give @s morefood:fry_wrapper
give @s morefood:fungus_stew
give @s morefood:gelatin
give @s morefood:gherkin
give @s morefood:gherkin_seeds
give @s morefood:cappuccino_drink_mix
give @s morefood:cheese_spread
give @s morefood:cheese_tortellini
give @s morefood:chicken_soup
give @s morefood:chili
give @s morefood:chocolate_banana_muffin
give @s morefood:chocolate_chunk_oatmeal_cookie
give @s morefood:chocolate_peanut_butter
give @s morefood:chocolate_protein_drink
give @s morefood:chocolate_protein_drink_mix
give @s morefood:chocolate_pudding
give @s morefood:cocoa_beverage
give @s morefood:cocoa_beverage_powder
give @s morefood:cooked_marshmallow_on_a_stick
give @s morefood:cornbread
give @s morefood:crackers
give @s morefood:crackers_with_cheese
give @s morefood:crackers_with_chocolate_peanut_butter
give @s morefood:crackers_with_glowberry_jam
give @s morefood:crackers_with_jalapeno_cheese
give @s morefood:crackers_with_jam
give @s morefood:crackers_with_peanut_butter
give @s morefood:cranberries
give @s morefood:dark_chocolate_covered_apple
give @s morefood:dried_cranberries
give @s morefood:dried_raisens
give @s morefood:eggplant
give @s morefood:eggplant_seeds
give @s morefood:garlic
give @s morefood:garlic_mashed_potatoes
give @s morefood:glowberry_jam
give @s morefood:glowberry_jelly_sandwich
give @s morefood:glowberry_juice
give @s morefood:glowberry_pie
give @s morefood:glowberry_soda
give @s morefood:grape_beverage
