give @s morefood:knife_golden
give @s morefood:grape
give @s morefood:grape_seeds
give @s morefood:hamburger
give @s morefood:hamburger_patty
give @s morefood:hoglin_meat
give @s morefood:hops
give @s morefood:hops_seeds
give @s morefood:hot_dog
give @s morefood:hot_dog_bun
give @s morefood:frankfurter_sausage
give @s morefood:hot_beverage_cup
give @s morefood:banana_ice_cream
give @s morefood:chocolate_ice_cream
give @s morefood:ice_cream_cone
give @s morefood:strawberry_ice_cream
give @s morefood:toffee_ice_cream
give @s morefood:vanilla_ice_cream
give @s morefood:ice_cream_bowl
give @s morefood:icing
give @s morefood:knife_iron
give @s morefood:jam
give @s morefood:jar
give @s morefood:jelly_sandwich
give @s morefood:kebab
give @s morefood:ketchup
give @s morefood:lemon
give @s morefood:lemon_sapling
give @s morefood:lettuce
give @s morefood:lettuce_seeds
give @s morefood:milk_chocolate
give @s morefood:muffin_bun
give @s morefood:netherite_apple
give @s morefood:knife_netherite
give @s morefood:netherwart_chicken_soup
give @s morefood:netherwart_mushroom_soup
give @s morefood:grape_beverage_powder
give @s morefood:guacamole
give @s morefood:hash_browns
give @s morefood:jalapeno_cheese_bucket
give @s morefood:jalapeno_cheese_pie
give @s morefood:jalapeno_cheese_spread
give @s morefood:jalapeno_cheese_toastie
give @s morefood:jalapeno_cheese_wedge
give @s morefood:large_bowl
give @s morefood:lemon_lime_beverage
give @s morefood:lemon_lime_beverage_powder
give @s morefood:maple_muffin
give @s morefood:maple_sap_bucket
give @s morefood:maple_syrup
give @s morefood:maple_syrup_bucket
give @s morefood:marshmallow
give @s morefood:marshmallow_on_a_stick
give @s morefood:mashed_potatoes
give @s morefood:milk_chocolate_covered_apple
give @s morefood:oatmeal
give @s morefood:oatmeal_cookie
give @s morefood:oats
give @s morefood:oat_seeds
give @s morefood:onion_rings
give @s morefood:orange_beverage
give @s morefood:orange_beverage_powder
give @s morefood:pancake_mix
give @s morefood:peanut
give @s morefood:peanut_butter
give @s morefood:peanut_butter_jelly_sandwich
give @s morefood:peanut_seeds
give @s morefood:peppermint_ring
give @s morefood:poisonous_sweet_potato
give @s morefood:poison_berries
give @s morefood:pork_sausage_burger
give @s morefood:pound_cake
