give @s morefood:popcorn
give @s morefood:popcorn_bucket
give @s morefood:rainbow_cake
give @s morefood:ramen_noodles
give @s morefood:raspberry
give @s morefood:raspberry_seeds
give @s morefood:redwhiteblue_cake
give @s morefood:rice
give @s morefood:rice_pudding
give @s morefood:rice_seeds
give @s morefood:rotten_porkchop
give @s morefood:truckle_of_cheese
give @s morefood:salt
give @s morefood:sashimi
give @s morefood:breakfast_sausage
give @s morefood:sausage_egg_muffin
give @s morefood:sausage_egg_sandwich
give @s morefood:shroomlight_slice
give @s morefood:soda_can
give @s morefood:spaghetti
give @s morefood:sparkling_water_bucket
give @s morefood:squid
give @s morefood:starch
give @s morefood:knife_stone
give @s morefood:strawberry
give @s morefood:strawberry_jelly
give @s morefood:strawberry_seeds
give @s morefood:submarine_sandwich_bun
give @s morefood:sushi
give @s morefood:taco
give @s morefood:tea_leaves
give @s morefood:tea_seeds
give @s morefood:toast
give @s morefood:toffee
give @s morefood:tomato
give @s morefood:cake_with_cherries
give @s morefood:cherries
give @s morefood:almond_sapling
give @s morefood:apple_ice_crush
give @s morefood:apple_juice
give @s morefood:apple_pie
give @s morefood:apple_raspberry_ice_crush
give @s morefood:apple_raspberry_pie
give @s morefood:apple_sapling
give @s morefood:apple_sauce
give @s morefood:apple_soda
give @s morefood:avocado_sapling
give @s morefood:banana_ice_cream
give @s morefood:banana_milkshake
give @s morefood:banana_sapling
give @s morefood:beef_pie
give @s morefood:beef_submarine_sandwich
give @s morefood:beer_mug
give @s morefood:berry_ice_crush
give @s morefood:berry_juice
give @s morefood:berry_pie
give @s morefood:berry_soda
give @s morefood:bread_slice
give @s morefood:bread_slice_with_cheese
give @s morefood:bread_slice_with_chocolate_peanut_butter
give @s morefood:bread_slice_with_glowberry_jam
give @s morefood:bread_slice_with_jalapeno_cheese
give @s morefood:bread_slice_with_jam
give @s morefood:bread_slice_with_peanut_butter
give @s morefood:breakfast_sausage
give @s morefood:breakfast_submarine_sandwich
give @s morefood:cheese_pie
give @s morefood:chicken_pie
give @s morefood:chicken_submarine_sandwich
give @s morefood:chocolate_doughnut
give @s morefood:chocolate_ice_cream
