give @s morefood:chocolate_milkshake
give @s morefood:chocolate_pie
give @s morefood:coffee_doughnut
give @s morefood:cooked_breakfast_sausage
give @s morefood:cooked_frankfurter_sausage
give @s morefood:cooked_potato_wedges
give @s morefood:cooked_veggie_burger_patty
give @s morefood:corncob
give @s morefood:frankfurter_sausage
give @s morefood:french_fries
give @s morefood:french_fry_pot
give @s morefood:glowberry_ice_crush
give @s morefood:grape_ice_crush
give @s morefood:grape_juice
give @s morefood:grape_soda
give @s morefood:hamburger_patty
give @s morefood:hot_dog
give @s morefood:hot_dog_bun
give @s morefood:iced_doughnut
give @s morefood:ice_cream_bowl
give @s morefood:ice_cream_cone
give @s morefood:ice_crush_glass
give @s morefood:lemon_ice_crush
give @s morefood:lemon_juice
give @s morefood:lemon_pie
give @s morefood:lemon_sapling
give @s morefood:lemon_soda
give @s morefood:melon_ice_crush
give @s morefood:melon_juice
give @s morefood:mixed_fruit_ice_crush
give @s morefood:mixed_fruit_juice
give @s morefood:olive_sapling
give @s morefood:orange_juice
give @s morefood:orange_sapling
give @s morefood:orange_soda
give @s morefood:palm_sapling
