give @s morefood:crackers_with_chocolate_peanut_butter
give @s morefood:crackers_with_glowberry_jam
give @s morefood:crackers_with_jalapeno_cheese
give @s morefood:crackers_with_jam
give @s morefood:crackers_with_peanut_butter
give @s morefood:cranberries
give @s morefood:cranberry_seeds
give @s morefood:bread_slice_with_cheese
give @s morefood:bread_slice_with_chocolate_peanut_butter
give @s morefood:bread_slice_with_glowberry_jam
give @s morefood:bread_slice_with_jalapeno_cheese
give @s morefood:bread_slice_with_jam
give @s morefood:bread_slice_with_peanut_butter
give @s morefood:sweet_french_fries
give @s morefood:dark_chocolate_covered_apple
give @s morefood:dried_cranberries
give @s morefood:dried_raisens
give @s morefood:chocolate_protein_drink
give @s morefood:cocoa_beverage
give @s morefood:glowberry_ice_crush
give @s morefood:glowberry_juice
give @s morefood:glowberry_smoothie
give @s morefood:glowberry_soda
give @s morefood:grape_beverage
give @s morefood:lemon_lime_beverage
give @s morefood:orange_beverage
give @s morefood:tropical_punch_beverage
give @s morefood:eggplant
give @s morefood:eggplant_seeds
give @s morefood:garlic
give @s morefood:garlic_bulb
give @s morefood:garlic_mashed_potatoes
give @s morefood:glass_shard
give @s morefood:glowberry_jam
give @s morefood:glowberry_jelly_sandwich
give @s morefood:glowberry_pie
give @s morefood:knife_diamond
give @s morefood:dough
give @s morefood:americano
give @s morefood:beer
give @s morefood:bottled_beer_0
give @s morefood:bottled_beer
give @s morefood:bottled_beer_25
give @s morefood:bottled_beer_50
give @s morefood:bottled_beer_75
give @s morefood:bottled_cider_0
give @s morefood:bottled_cider
give @s morefood:bottled_cider_25
give @s morefood:bottled_cider_50
give @s morefood:bottled_cider_75
give @s morefood:bottled_red_wine_0
give @s morefood:bottled_red_wine
give @s morefood:bottled_red_wine_25
give @s morefood:bottled_red_wine_50
give @s morefood:bottled_red_wine_75
give @s morefood:bottled_white_wine_0
give @s morefood:bottled_white_wine
give @s morefood:bottled_white_wine_25
give @s morefood:bottled_white_wine_50
give @s morefood:bottled_white_wine_75
give @s morefood:cappuccino
give @s morefood:cider
give @s morefood:coconut_milk
give @s morefood:cream_bottle
give @s morefood:hot_cocoa
give @s morefood:hot_coffee
give @s morefood:hot_tea
give @s morefood:orange_ice_crush
give @s morefood:macchiato
give @s morefood:milk_bottle
give @s morefood:mocha
give @s morefood:oil
