give @s morefood:cream_bottle
give @s morefood:glowberry_smoothie
give @s morefood:grape_smoothie
give @s morefood:milk_bottle
give @s morefood:mixed_fruit_smoothie
give @s morefood:raspberry_smoothie
give @s morefood:smoothie_cup
give @s morefood:strawberry_smoothie
give @s morefood:sweet_corn
give @s morefood:sweet_french_fries
give @s morefood:rainbow_cake
give @s morefood:ramen_noodles
give @s morefood:raspberry
give @s morefood:raspberry_seeds
give @s morefood:meal_ready_to_eat
give @s morefood:redwhiteblue_cake
give @s morefood:rice
give @s morefood:rice_pudding
give @s morefood:rice_seeds
give @s morefood:rotten_porkchop
give @s morefood:salt
give @s morefood:sashimi
give @s morefood:sausage_egg_muffin
give @s morefood:sausage_egg_sandwich
give @s morefood:spaghetti
give @s morefood:sparkling_water_bucket
give @s morefood:starch
give @s morefood:knife_stone
give @s morefood:strawberry
give @s morefood:strawberry_jelly
give @s morefood:strawberry_seeds
give @s morefood:sushi
give @s morefood:taco
give @s morefood:tea_leaves
give @s morefood:tea_seeds
give @s morefood:toast
