give @s morefood:nether_cookie
give @s morefood:noodles
give @s morefood:olives
give @s morefood:olive_sapling
give @s morefood:onigiri
give @s morefood:onion
give @s morefood:onion_seeds
give @s morefood:orange
give @s morefood:orange_jelly
give @s morefood:orange_sapling
give @s morefood:palm_sapling
give @s morefood:pancakes
give @s morefood:pasta
give @s morefood:pepper
give @s morefood:pepper_seeds
give @s morefood:pickles
give @s morefood:apple_pie
give @s morefood:apple_raspberry_pie
give @s morefood:pie_crust
give @s morefood:berry_pie
give @s morefood:cheese_pie
give @s morefood:chicken_pie
give @s morefood:chocolate_pie
give @s morefood:lemon_pie
give @s morefood:plum_pie
give @s morefood:pork_pie
give @s morefood:beef_pie
give @s morefood:strawberry_pie
give @s morefood:toffee_pie
give @s morefood:pink_cupcake
give @s morefood:pitta_bread
give @s morefood:pizza
give @s morefood:pizza_crust
give @s morefood:pizza_slice
give @s morefood:plum
give @s morefood:plum_sapling
give @s morefood:pretzel_nuggets
give @s morefood:pretzel_sticks
give @s morefood:pulled_beef_burger
give @s morefood:raspberry_syrup
give @s morefood:roasted_peanut
give @s morefood:roasted_soybeans
give @s morefood:roasted_sunflower_seeds
give @s morefood:smoked_almonds
give @s morefood:soybeans
give @s morefood:spaghetti_with_meatballs
give @s morefood:spinach
give @s morefood:spinach_fettuccine
give @s morefood:spinach_seeds
give @s morefood:strawberry_syrup
give @s morefood:sugar_cookie
give @s morefood:sweet_mashed_potatoes
give @s morefood:sweet_potato
give @s morefood:tortilla_chips
give @s morefood:tortilla_with_cheese
give @s morefood:tortilla_with_jalapeno_cheese
give @s morefood:trail_mix
give @s morefood:tropical_punch_beverage
give @s morefood:tropical_punch_beverage_powder
give @s morefood:tuna_sandwich
give @s morefood:vanilla_pudding
give @s morefood:white_chocolate_covered_apple
give @s morefood:wooden_tree_tap.item
give @s morefood:bean_seeds
give @s morefood:cranberry_seeds
give @s morefood:garlic_bulb
give @s morefood:glass_shard
give @s morefood:peppermint
give @s morefood:peppermint_extract
give @s morefood:peppermint_seeds
give @s morefood:pretzel
give @s morefood:pulp
