give @s morefood:pie_crust
give @s morefood:pink_ice_doughnut
give @s morefood:pizza_crust
give @s morefood:plain_doughnut
give @s morefood:plum_pie
give @s morefood:plum_sapling
give @s morefood:pork_pie
give @s morefood:potato_wedges
give @s morefood:potato_wedges_pot
give @s morefood:shroomlight_slice
give @s morefood:soda_can
give @s morefood:spearmint
give @s morefood:squid
give @s morefood:strawberry_doughnut
give @s morefood:strawberry_ice_cream
give @s morefood:strawberry_ice_crush
give @s morefood:strawberry_juice
give @s morefood:strawberry_milkshake
give @s morefood:strawberry_pie
give @s morefood:strawberry_soda
give @s morefood:submarine_sandwich_bun
give @s morefood:sweet_french_fry_pot
give @s morefood:toffee_doughnut
give @s morefood:toffee_ice_cream
give @s morefood:toffee_pie
give @s morefood:tomato_juice
give @s morefood:truckle_of_jalapeno_cheese
give @s morefood:truckle_of_cheese
give @s morefood:tumbler_glass
give @s morefood:vanilla_ice_cream
give @s morefood:veggie_burger
give @s morefood:veggie_burger_patty
give @s morefood:watermint
give @s morefood:banana_smoothie
give @s morefood:berry_smoothie
give @s morefood:corn_starch
